# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ajuste.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(492, 431)
        self.formFrame = QtWidgets.QFrame(Form)
        self.formFrame.setGeometry(QtCore.QRect(30, 70, 211, 231))
        self.formFrame.setObjectName("formFrame")
        self.formLayout = QtWidgets.QFormLayout(self.formFrame)
        self.formLayout.setObjectName("formLayout")
        self.contaCorrente1Label = QtWidgets.QLabel(self.formFrame)
        self.contaCorrente1Label.setObjectName("contaCorrente1Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.contaCorrente1Label)
        self.spinConta1 = QtWidgets.QDoubleSpinBox(self.formFrame)
        self.spinConta1.setMaximum(9999.99)
        self.spinConta1.setObjectName("spinConta1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinConta1)
        self.poupanca1Label = QtWidgets.QLabel(self.formFrame)
        self.poupanca1Label.setObjectName("poupanca1Label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.poupanca1Label)
        self.spinPoupanca = QtWidgets.QDoubleSpinBox(self.formFrame)
        self.spinPoupanca.setMaximum(9999.99)
        self.spinPoupanca.setObjectName("spinPoupanca")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinPoupanca)
        self.contaCorrente2Label = QtWidgets.QLabel(self.formFrame)
        self.contaCorrente2Label.setObjectName("contaCorrente2Label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.contaCorrente2Label)
        self.spintConta2 = QtWidgets.QDoubleSpinBox(self.formFrame)
        self.spintConta2.setMaximum(9999.99)
        self.spintConta2.setObjectName("spintConta2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spintConta2)
        self.poupanca2Label = QtWidgets.QLabel(self.formFrame)
        self.poupanca2Label.setObjectName("poupanca2Label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.poupanca2Label)
        self.spinPoupanca2 = QtWidgets.QDoubleSpinBox(self.formFrame)
        self.spinPoupanca2.setMaximum(9999.99)
        self.spinPoupanca2.setObjectName("spinPoupanca2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinPoupanca2)
        self.cateiraLabel = QtWidgets.QLabel(self.formFrame)
        self.cateiraLabel.setObjectName("cateiraLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.cateiraLabel)
        self.spinCarteira = QtWidgets.QDoubleSpinBox(self.formFrame)
        self.spinCarteira.setMaximum(9999.99)
        self.spinCarteira.setObjectName("spinCarteira")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinCarteira)
        self.cartaoDeCreditoLabel = QtWidgets.QLabel(self.formFrame)
        self.cartaoDeCreditoLabel.setObjectName("cartaoDeCreditoLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.cartaoDeCreditoLabel)
        self.spinCredito1 = QtWidgets.QDoubleSpinBox(self.formFrame)
        self.spinCredito1.setMaximum(9999.99)
        self.spinCredito1.setObjectName("spinCredito1")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinCredito1)
        self.ajusteLabel = QtWidgets.QLabel(self.formFrame)
        self.ajusteLabel.setObjectName("ajusteLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.ajusteLabel)
        self.spinAjusteP = QtWidgets.QDoubleSpinBox(self.formFrame)
        self.spinAjusteP.setMaximum(9999.99)
        self.spinAjusteP.setObjectName("spinAjusteP")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.spinAjusteP)
        self.spinAjusteN = QtWidgets.QDoubleSpinBox(self.formFrame)
        self.spinAjusteN.setMaximum(9999.99)
        self.spinAjusteN.setObjectName("spinAjusteN")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.spinAjusteN)
        self.ajusteLabel_2 = QtWidgets.QLabel(self.formFrame)
        self.ajusteLabel_2.setObjectName("ajusteLabel_2")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.ajusteLabel_2)
        self.cartaoDeCreditoLabel_2 = QtWidgets.QLabel(self.formFrame)
        self.cartaoDeCreditoLabel_2.setObjectName("cartaoDeCreditoLabel_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.cartaoDeCreditoLabel_2)
        self.spinCredito2 = QtWidgets.QDoubleSpinBox(self.formFrame)
        self.spinCredito2.setMaximum(9999.99)
        self.spinCredito2.setObjectName("spinCredito2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinCredito2)
        self.gridGroupBox = QtWidgets.QGroupBox(Form)
        self.gridGroupBox.setGeometry(QtCore.QRect(270, 90, 191, 181))
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.gridGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.r1Label = QtWidgets.QLabel(self.gridGroupBox)
        self.r1Label.setObjectName("r1Label")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.r1Label)
        self.spin1 = QtWidgets.QSpinBox(self.gridGroupBox)
        self.spin1.setObjectName("spin1")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spin1)
        self.r050Label = QtWidgets.QLabel(self.gridGroupBox)
        self.r050Label.setObjectName("r050Label")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.r050Label)
        self.spin05 = QtWidgets.QSpinBox(self.gridGroupBox)
        self.spin05.setObjectName("spin05")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spin05)
        self.r025Label = QtWidgets.QLabel(self.gridGroupBox)
        self.r025Label.setObjectName("r025Label")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.r025Label)
        self.spin025 = QtWidgets.QSpinBox(self.gridGroupBox)
        self.spin025.setObjectName("spin025")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spin025)
        self.r010Label = QtWidgets.QLabel(self.gridGroupBox)
        self.r010Label.setObjectName("r010Label")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.r010Label)
        self.spin01 = QtWidgets.QSpinBox(self.gridGroupBox)
        self.spin01.setObjectName("spin01")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spin01)
        self.r005Label = QtWidgets.QLabel(self.gridGroupBox)
        self.r005Label.setObjectName("r005Label")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.r005Label)
        self.spin005 = QtWidgets.QSpinBox(self.gridGroupBox)
        self.spin005.setObjectName("spin005")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spin005)
        self.r001Label = QtWidgets.QLabel(self.gridGroupBox)
        self.r001Label.setObjectName("r001Label")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.r001Label)
        self.spin001 = QtWidgets.QSpinBox(self.gridGroupBox)
        self.spin001.setObjectName("spin001")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spin001)
        self.gridLayout.addLayout(self.formLayout_5, 0, 1, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.r100Label = QtWidgets.QLabel(self.gridGroupBox)
        self.r100Label.setObjectName("r100Label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.r100Label)
        self.spin100 = QtWidgets.QSpinBox(self.gridGroupBox)
        self.spin100.setMaximum(999)
        self.spin100.setObjectName("spin100")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spin100)
        self.r50Label = QtWidgets.QLabel(self.gridGroupBox)
        self.r50Label.setObjectName("r50Label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.r50Label)
        self.spin50 = QtWidgets.QSpinBox(self.gridGroupBox)
        self.spin50.setObjectName("spin50")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spin50)
        self.r20Label = QtWidgets.QLabel(self.gridGroupBox)
        self.r20Label.setObjectName("r20Label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.r20Label)
        self.spin20 = QtWidgets.QSpinBox(self.gridGroupBox)
        self.spin20.setObjectName("spin20")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spin20)
        self.r10Label = QtWidgets.QLabel(self.gridGroupBox)
        self.r10Label.setObjectName("r10Label")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.r10Label)
        self.spin10 = QtWidgets.QSpinBox(self.gridGroupBox)
        self.spin10.setObjectName("spin10")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spin10)
        self.r5Label = QtWidgets.QLabel(self.gridGroupBox)
        self.r5Label.setObjectName("r5Label")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.r5Label)
        self.spin5 = QtWidgets.QSpinBox(self.gridGroupBox)
        self.spin5.setObjectName("spin5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spin5)
        self.r2Label = QtWidgets.QLabel(self.gridGroupBox)
        self.r2Label.setObjectName("r2Label")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.r2Label)
        self.spin2 = QtWidgets.QSpinBox(self.gridGroupBox)
        self.spin2.setObjectName("spin2")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spin2)
        self.gridLayout.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 471, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.labelReserva = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelReserva.setObjectName("labelReserva")
        self.horizontalLayout.addWidget(self.labelReserva)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.labelResto = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelResto.setObjectName("labelResto")
        self.horizontalLayout.addWidget(self.labelResto)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.labelSoma = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelSoma.setObjectName("labelSoma")
        self.horizontalLayout.addWidget(self.labelSoma)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(100, 310, 301, 53))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelAjuste = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelAjuste.setObjectName("labelAjuste")
        self.gridLayout_2.addWidget(self.labelAjuste, 1, 1, 1, 1)
        self.labelTenho = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelTenho.setObjectName("labelTenho")
        self.gridLayout_2.addWidget(self.labelTenho, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 2, 1, 1)
        self.labelApp = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelApp.setObjectName("labelApp")
        self.gridLayout_2.addWidget(self.labelApp, 0, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(210, 400, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(100, 370, 301, 25))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelAdd = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelAdd.setObjectName("labelAdd")
        self.horizontalLayout_2.addWidget(self.labelAdd)
        self.botaoAdd = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.botaoAdd.setObjectName("botaoAdd")
        self.horizontalLayout_2.addWidget(self.botaoAdd)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.spinConta1, self.spinPoupanca)
        Form.setTabOrder(self.spinPoupanca, self.spintConta2)
        Form.setTabOrder(self.spintConta2, self.spinPoupanca2)
        Form.setTabOrder(self.spinPoupanca2, self.spinCarteira)
        Form.setTabOrder(self.spinCarteira, self.spinCredito1)
        Form.setTabOrder(self.spinCredito1, self.spinCredito2)
        Form.setTabOrder(self.spinCredito2, self.spinAjusteP)
        Form.setTabOrder(self.spinAjusteP, self.spinAjusteN)
        Form.setTabOrder(self.spinAjusteN, self.spin100)
        Form.setTabOrder(self.spin100, self.spin50)
        Form.setTabOrder(self.spin50, self.spin20)
        Form.setTabOrder(self.spin20, self.spin10)
        Form.setTabOrder(self.spin10, self.spin5)
        Form.setTabOrder(self.spin5, self.spin2)
        Form.setTabOrder(self.spin2, self.spin1)
        Form.setTabOrder(self.spin1, self.spin05)
        Form.setTabOrder(self.spin05, self.spin025)
        Form.setTabOrder(self.spin025, self.spin01)
        Form.setTabOrder(self.spin01, self.spin005)
        Form.setTabOrder(self.spin005, self.spin001)
        Form.setTabOrder(self.spin001, self.pushButton)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Dívida"))
        self.contaCorrente1Label.setText(_translate("Form", "Conta Corrente 1"))
        self.poupanca1Label.setText(_translate("Form", "Poupança 1"))
        self.contaCorrente2Label.setText(_translate("Form", "Conta Corrente 2"))
        self.poupanca2Label.setText(_translate("Form", "Poupança 2"))
        self.cateiraLabel.setText(_translate("Form", "Carteira"))
        self.cartaoDeCreditoLabel.setText(_translate("Form", "Cartão de Crédito 1"))
        self.ajusteLabel.setText(_translate("Form", "Ajuste +"))
        self.ajusteLabel_2.setText(_translate("Form", "Ajuste -"))
        self.cartaoDeCreditoLabel_2.setText(_translate("Form", "Cartão de Crédito 2"))
        self.gridGroupBox.setTitle(_translate("Form", "Carteira"))
        self.r1Label.setText(_translate("Form", "R$1"))
        self.r050Label.setText(_translate("Form", "R$0,50"))
        self.r025Label.setText(_translate("Form", "R$0,25"))
        self.r010Label.setText(_translate("Form", "R$0,10"))
        self.r005Label.setText(_translate("Form", "R$0,05"))
        self.r001Label.setText(_translate("Form", "R$0,01"))
        self.r100Label.setText(_translate("Form", "R$100"))
        self.r50Label.setText(_translate("Form", "R$50"))
        self.r20Label.setText(_translate("Form", "R$20"))
        self.r10Label.setText(_translate("Form", "R$10"))
        self.r5Label.setText(_translate("Form", "R$5"))
        self.r2Label.setText(_translate("Form", "R$2"))
        self.label.setText(_translate("Form", "Reserva:"))
        self.labelReserva.setText(_translate("Form", "{reserva}"))
        self.label_3.setText(_translate("Form", "Resto:"))
        self.labelResto.setText(_translate("Form", "{resto}"))
        self.label_5.setText(_translate("Form", "Soma:"))
        self.labelSoma.setText(_translate("Form", "{soma}"))
        self.labelAjuste.setText(_translate("Form", "{valor}"))
        self.labelTenho.setText(_translate("Form", "{tenho}"))
        self.label_7.setText(_translate("Form", "Valor real:"))
        self.label_9.setText(_translate("Form", "Valor no aplicativo:"))
        self.labelApp.setText(_translate("Form", "{app}"))
        self.label_11.setText(_translate("Form", "Ajuste:"))
        self.pushButton.setText(_translate("Form", "OK"))
        self.labelAdd.setText(_translate("Form", "{Add Entrada/Fixo}"))
        self.botaoAdd.setText(_translate("Form", "{Adicionar}"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

