# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ajuste.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(501, 534)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.labelAjustes = QtWidgets.QLabel(Form)
        self.labelAjustes.setObjectName("labelAjustes")
        self.horizontalLayout.addWidget(self.labelAjustes)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.labelReserva = QtWidgets.QLabel(Form)
        self.labelReserva.setObjectName("labelReserva")
        self.horizontalLayout.addWidget(self.labelReserva)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.labelResto = QtWidgets.QLabel(Form)
        self.labelResto.setObjectName("labelResto")
        self.horizontalLayout.addWidget(self.labelResto)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.labelSoma = QtWidgets.QLabel(Form)
        self.labelSoma.setObjectName("labelSoma")
        self.horizontalLayout.addWidget(self.labelSoma)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formFrame = QtWidgets.QFrame(Form)
        self.formFrame.setObjectName("formFrame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.formFrame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.spinAjusteN = QtWidgets.QDoubleSpinBox(self.formFrame)
        self.spinAjusteN.setMaximum(9999.99)
        self.spinAjusteN.setObjectName("spinAjusteN")
        self.gridLayout_5.addWidget(self.spinAjusteN, 11, 1, 1, 1)
        self.spinConta3 = QtWidgets.QDoubleSpinBox(self.formFrame)
        self.spinConta3.setMaximum(9999.99)
        self.spinConta3.setObjectName("spinConta3")
        self.gridLayout_5.addWidget(self.spinConta3, 2, 1, 1, 1)
        self.cateiraLabel = QtWidgets.QLabel(self.formFrame)
        self.cateiraLabel.setObjectName("cateiraLabel")
        self.gridLayout_5.addWidget(self.cateiraLabel, 6, 0, 1, 1)
        self.contaCorrente3Label = QtWidgets.QLabel(self.formFrame)
        self.contaCorrente3Label.setObjectName("contaCorrente3Label")
        self.gridLayout_5.addWidget(self.contaCorrente3Label, 2, 0, 1, 1)
        self.spinAjusteP = QtWidgets.QDoubleSpinBox(self.formFrame)
        self.spinAjusteP.setMaximum(9999.99)
        self.spinAjusteP.setObjectName("spinAjusteP")
        self.gridLayout_5.addWidget(self.spinAjusteP, 10, 1, 1, 1)
        self.poupanca1Label = QtWidgets.QLabel(self.formFrame)
        self.poupanca1Label.setObjectName("poupanca1Label")
        self.gridLayout_5.addWidget(self.poupanca1Label, 4, 0, 1, 1)
        self.spinConta1 = QtWidgets.QDoubleSpinBox(self.formFrame)
        self.spinConta1.setMaximum(9999.99)
        self.spinConta1.setObjectName("spinConta1")
        self.gridLayout_5.addWidget(self.spinConta1, 0, 1, 1, 1)
        self.spinConta2 = QtWidgets.QDoubleSpinBox(self.formFrame)
        self.spinConta2.setMaximum(9999.99)
        self.spinConta2.setObjectName("spinConta2")
        self.gridLayout_5.addWidget(self.spinConta2, 1, 1, 1, 1)
        self.contaCorrente1Label = QtWidgets.QLabel(self.formFrame)
        self.contaCorrente1Label.setObjectName("contaCorrente1Label")
        self.gridLayout_5.addWidget(self.contaCorrente1Label, 0, 0, 1, 1)
        self.ajusteLabel = QtWidgets.QLabel(self.formFrame)
        self.ajusteLabel.setObjectName("ajusteLabel")
        self.gridLayout_5.addWidget(self.ajusteLabel, 10, 0, 1, 1)
        self.spinPoupanca = QtWidgets.QDoubleSpinBox(self.formFrame)
        self.spinPoupanca.setMaximum(9999.99)
        self.spinPoupanca.setObjectName("spinPoupanca")
        self.gridLayout_5.addWidget(self.spinPoupanca, 4, 1, 1, 1)
        self.poupanca2Label = QtWidgets.QLabel(self.formFrame)
        self.poupanca2Label.setObjectName("poupanca2Label")
        self.gridLayout_5.addWidget(self.poupanca2Label, 5, 0, 1, 1)
        self.spinPoupanca2 = QtWidgets.QDoubleSpinBox(self.formFrame)
        self.spinPoupanca2.setMaximum(9999.99)
        self.spinPoupanca2.setObjectName("spinPoupanca2")
        self.gridLayout_5.addWidget(self.spinPoupanca2, 5, 1, 1, 1)
        self.contaCorrente2Label = QtWidgets.QLabel(self.formFrame)
        self.contaCorrente2Label.setObjectName("contaCorrente2Label")
        self.gridLayout_5.addWidget(self.contaCorrente2Label, 1, 0, 1, 1)
        self.spinCarteira = QtWidgets.QDoubleSpinBox(self.formFrame)
        self.spinCarteira.setMaximum(9999.99)
        self.spinCarteira.setObjectName("spinCarteira")
        self.gridLayout_5.addWidget(self.spinCarteira, 6, 1, 1, 1)
        self.ajusteLabel_2 = QtWidgets.QLabel(self.formFrame)
        self.ajusteLabel_2.setObjectName("ajusteLabel_2")
        self.gridLayout_5.addWidget(self.ajusteLabel_2, 11, 0, 1, 1)
        self.cartaoDeCreditoLabel_2 = QtWidgets.QLabel(self.formFrame)
        self.cartaoDeCreditoLabel_2.setObjectName("cartaoDeCreditoLabel_2")
        self.gridLayout_5.addWidget(self.cartaoDeCreditoLabel_2, 9, 0, 1, 1)
        self.cartaoDeCreditoLabel = QtWidgets.QLabel(self.formFrame)
        self.cartaoDeCreditoLabel.setObjectName("cartaoDeCreditoLabel")
        self.gridLayout_5.addWidget(self.cartaoDeCreditoLabel, 8, 0, 1, 1)
        self.spinCredito1 = QtWidgets.QDoubleSpinBox(self.formFrame)
        self.spinCredito1.setMaximum(9999.99)
        self.spinCredito1.setObjectName("spinCredito1")
        self.gridLayout_5.addWidget(self.spinCredito1, 8, 1, 1, 1)
        self.spinCredito2 = QtWidgets.QDoubleSpinBox(self.formFrame)
        self.spinCredito2.setMaximum(9999.99)
        self.spinCredito2.setObjectName("spinCredito2")
        self.gridLayout_5.addWidget(self.spinCredito2, 9, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.formFrame)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.gridGroupBox = QtWidgets.QGroupBox(Form)
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.gridGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.r1Label = QtWidgets.QLabel(self.gridGroupBox)
        self.r1Label.setObjectName("r1Label")
        self.gridLayout_4.addWidget(self.r1Label, 0, 0, 1, 1)
        self.spin1 = QtWidgets.QSpinBox(self.gridGroupBox)
        self.spin1.setObjectName("spin1")
        self.gridLayout_4.addWidget(self.spin1, 0, 1, 1, 1)
        self.r050Label = QtWidgets.QLabel(self.gridGroupBox)
        self.r050Label.setObjectName("r050Label")
        self.gridLayout_4.addWidget(self.r050Label, 1, 0, 1, 1)
        self.spin05 = QtWidgets.QSpinBox(self.gridGroupBox)
        self.spin05.setObjectName("spin05")
        self.gridLayout_4.addWidget(self.spin05, 1, 1, 1, 1)
        self.r025Label = QtWidgets.QLabel(self.gridGroupBox)
        self.r025Label.setObjectName("r025Label")
        self.gridLayout_4.addWidget(self.r025Label, 2, 0, 1, 1)
        self.spin025 = QtWidgets.QSpinBox(self.gridGroupBox)
        self.spin025.setObjectName("spin025")
        self.gridLayout_4.addWidget(self.spin025, 2, 1, 1, 1)
        self.r010Label = QtWidgets.QLabel(self.gridGroupBox)
        self.r010Label.setObjectName("r010Label")
        self.gridLayout_4.addWidget(self.r010Label, 3, 0, 1, 1)
        self.spin01 = QtWidgets.QSpinBox(self.gridGroupBox)
        self.spin01.setObjectName("spin01")
        self.gridLayout_4.addWidget(self.spin01, 3, 1, 1, 1)
        self.r005Label = QtWidgets.QLabel(self.gridGroupBox)
        self.r005Label.setObjectName("r005Label")
        self.gridLayout_4.addWidget(self.r005Label, 4, 0, 1, 1)
        self.spin005 = QtWidgets.QSpinBox(self.gridGroupBox)
        self.spin005.setObjectName("spin005")
        self.gridLayout_4.addWidget(self.spin005, 4, 1, 1, 1)
        self.r001Label = QtWidgets.QLabel(self.gridGroupBox)
        self.r001Label.setObjectName("r001Label")
        self.gridLayout_4.addWidget(self.r001Label, 5, 0, 1, 1)
        self.spin001 = QtWidgets.QSpinBox(self.gridGroupBox)
        self.spin001.setObjectName("spin001")
        self.gridLayout_4.addWidget(self.spin001, 5, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.r10Label = QtWidgets.QLabel(self.gridGroupBox)
        self.r10Label.setObjectName("r10Label")
        self.gridLayout_3.addWidget(self.r10Label, 3, 0, 1, 1)
        self.spin20 = QtWidgets.QSpinBox(self.gridGroupBox)
        self.spin20.setObjectName("spin20")
        self.gridLayout_3.addWidget(self.spin20, 2, 1, 1, 1)
        self.r5Label = QtWidgets.QLabel(self.gridGroupBox)
        self.r5Label.setObjectName("r5Label")
        self.gridLayout_3.addWidget(self.r5Label, 4, 0, 1, 1)
        self.r2Label = QtWidgets.QLabel(self.gridGroupBox)
        self.r2Label.setObjectName("r2Label")
        self.gridLayout_3.addWidget(self.r2Label, 5, 0, 1, 1)
        self.spin10 = QtWidgets.QSpinBox(self.gridGroupBox)
        self.spin10.setObjectName("spin10")
        self.gridLayout_3.addWidget(self.spin10, 3, 1, 1, 1)
        self.spin2 = QtWidgets.QSpinBox(self.gridGroupBox)
        self.spin2.setObjectName("spin2")
        self.gridLayout_3.addWidget(self.spin2, 5, 1, 1, 1)
        self.spin5 = QtWidgets.QSpinBox(self.gridGroupBox)
        self.spin5.setObjectName("spin5")
        self.gridLayout_3.addWidget(self.spin5, 4, 1, 1, 1)
        self.spin50 = QtWidgets.QSpinBox(self.gridGroupBox)
        self.spin50.setObjectName("spin50")
        self.gridLayout_3.addWidget(self.spin50, 1, 1, 1, 1)
        self.r50Label = QtWidgets.QLabel(self.gridGroupBox)
        self.r50Label.setObjectName("r50Label")
        self.gridLayout_3.addWidget(self.r50Label, 1, 0, 1, 1)
        self.spin100 = QtWidgets.QSpinBox(self.gridGroupBox)
        self.spin100.setMaximum(999)
        self.spin100.setObjectName("spin100")
        self.gridLayout_3.addWidget(self.spin100, 0, 1, 1, 1)
        self.r20Label = QtWidgets.QLabel(self.gridGroupBox)
        self.r20Label.setObjectName("r20Label")
        self.gridLayout_3.addWidget(self.r20Label, 2, 0, 1, 1)
        self.r100Label = QtWidgets.QLabel(self.gridGroupBox)
        self.r100Label.setObjectName("r100Label")
        self.gridLayout_3.addWidget(self.r100Label, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.gridGroupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.labelTenho = QtWidgets.QLabel(Form)
        self.labelTenho.setObjectName("labelTenho")
        self.horizontalLayout_5.addWidget(self.labelTenho)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.labelApp = QtWidgets.QLabel(Form)
        self.labelApp.setObjectName("labelApp")
        self.horizontalLayout_5.addWidget(self.labelApp)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.labelAjuste = QtWidgets.QLabel(Form)
        self.labelAjuste.setObjectName("labelAjuste")
        self.horizontalLayout_2.addWidget(self.labelAjuste)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelAdd = QtWidgets.QLabel(Form)
        self.labelAdd.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAdd.setObjectName("labelAdd")
        self.verticalLayout_3.addWidget(self.labelAdd)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.botaoAtualizar = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botaoAtualizar.sizePolicy().hasHeightForWidth())
        self.botaoAtualizar.setSizePolicy(sizePolicy)
        self.botaoAtualizar.setObjectName("botaoAtualizar")
        self.verticalLayout_2.addWidget(self.botaoAtualizar)
        self.botaoAdd = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botaoAdd.sizePolicy().hasHeightForWidth())
        self.botaoAdd.setSizePolicy(sizePolicy)
        self.botaoAdd.setObjectName("botaoAdd")
        self.verticalLayout_2.addWidget(self.botaoAdd)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.spinConta1, self.spinConta2)
        Form.setTabOrder(self.spinConta2, self.spinConta3)
        Form.setTabOrder(self.spinConta3, self.spinPoupanca)
        Form.setTabOrder(self.spinPoupanca, self.spinPoupanca2)
        Form.setTabOrder(self.spinPoupanca2, self.spin100)
        Form.setTabOrder(self.spin100, self.spin50)
        Form.setTabOrder(self.spin50, self.spin20)
        Form.setTabOrder(self.spin20, self.spin10)
        Form.setTabOrder(self.spin10, self.spin5)
        Form.setTabOrder(self.spin5, self.spin2)
        Form.setTabOrder(self.spin2, self.spin1)
        Form.setTabOrder(self.spin1, self.spin05)
        Form.setTabOrder(self.spin05, self.spin025)
        Form.setTabOrder(self.spin025, self.spin01)
        Form.setTabOrder(self.spin01, self.spin005)
        Form.setTabOrder(self.spin005, self.spin001)
        Form.setTabOrder(self.spin001, self.spinCarteira)
        Form.setTabOrder(self.spinCarteira, self.spinCredito1)
        Form.setTabOrder(self.spinCredito1, self.spinCredito2)
        Form.setTabOrder(self.spinCredito2, self.spinAjusteP)
        Form.setTabOrder(self.spinAjusteP, self.spinAjusteN)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Dívida"))
        self.label_2.setText(_translate("Form", "Ajustes:"))
        self.labelAjustes.setText(_translate("Form", "{ajustes}"))
        self.label.setText(_translate("Form", "Reserva:"))
        self.labelReserva.setText(_translate("Form", "{reserva}"))
        self.label_3.setText(_translate("Form", "Resto:"))
        self.labelResto.setText(_translate("Form", "{resto}"))
        self.label_5.setText(_translate("Form", "Soma:"))
        self.labelSoma.setText(_translate("Form", "{soma}"))
        self.cateiraLabel.setText(_translate("Form", "Carteira"))
        self.contaCorrente3Label.setText(_translate("Form", "Conta Corrente 3"))
        self.poupanca1Label.setText(_translate("Form", "Poupança 1"))
        self.contaCorrente1Label.setText(_translate("Form", "Conta Corrente 1"))
        self.ajusteLabel.setText(_translate("Form", "Ajuste +"))
        self.poupanca2Label.setText(_translate("Form", "Poupança 2"))
        self.contaCorrente2Label.setText(_translate("Form", "Conta Corrente 2"))
        self.ajusteLabel_2.setText(_translate("Form", "Ajuste -"))
        self.cartaoDeCreditoLabel_2.setText(_translate("Form", "Cartão de Crédito 2"))
        self.cartaoDeCreditoLabel.setText(_translate("Form", "Cartão de Crédito 1"))
        self.gridGroupBox.setTitle(_translate("Form", "Carteira"))
        self.r1Label.setText(_translate("Form", "R$1"))
        self.r050Label.setText(_translate("Form", "R$0,50"))
        self.r025Label.setText(_translate("Form", "R$0,25"))
        self.r010Label.setText(_translate("Form", "R$0,10"))
        self.r005Label.setText(_translate("Form", "R$0,05"))
        self.r001Label.setText(_translate("Form", "R$0,01"))
        self.r10Label.setText(_translate("Form", "R$10"))
        self.r5Label.setText(_translate("Form", "R$5"))
        self.r2Label.setText(_translate("Form", "R$2"))
        self.r50Label.setText(_translate("Form", "R$50"))
        self.r20Label.setText(_translate("Form", "R$20"))
        self.r100Label.setText(_translate("Form", "R$100"))
        self.label_7.setText(_translate("Form", "Valor real:"))
        self.labelTenho.setText(_translate("Form", "{tenho}"))
        self.label_9.setText(_translate("Form", "Valor no aplicativo:"))
        self.labelApp.setText(_translate("Form", "{app}"))
        self.label_11.setText(_translate("Form", "Ajuste:"))
        self.labelAjuste.setText(_translate("Form", "{valor}"))
        self.labelAdd.setText(_translate("Form", "{Add Entrada/Fixo}"))
        self.botaoAtualizar.setText(_translate("Form", "Atualizar ajuste"))
        self.botaoAdd.setText(_translate("Form", "{Adicionar}"))
        self.pushButton.setText(_translate("Form", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

