# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'divida_pagar.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(690, 330)
        Form.setMinimumSize(QtCore.QSize(690, 330))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelValor = QtWidgets.QLabel(Form)
        self.labelValor.setObjectName("labelValor")
        self.horizontalLayout.addWidget(self.labelValor)
        self.labelValor_2 = QtWidgets.QLabel(Form)
        self.labelValor_2.setObjectName("labelValor_2")
        self.horizontalLayout.addWidget(self.labelValor_2)
        self.spinValor = QtWidgets.QDoubleSpinBox(Form)
        self.spinValor.setDecimals(2)
        self.spinValor.setMaximum(99999.99)
        self.spinValor.setProperty("value", 0.0)
        self.spinValor.setObjectName("spinValor")
        self.horizontalLayout.addWidget(self.spinValor)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.boxSaidas_3 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxSaidas_3.sizePolicy().hasHeightForWidth())
        self.boxSaidas_3.setSizePolicy(sizePolicy)
        self.boxSaidas_3.setMinimumSize(QtCore.QSize(0, 0))
        self.boxSaidas_3.setObjectName("boxSaidas_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.boxSaidas_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.treeDevo = QtWidgets.QTreeWidget(self.boxSaidas_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeDevo.sizePolicy().hasHeightForWidth())
        self.treeDevo.setSizePolicy(sizePolicy)
        self.treeDevo.setMinimumSize(QtCore.QSize(300, 0))
        self.treeDevo.setAlternatingRowColors(True)
        self.treeDevo.setRootIsDecorated(True)
        self.treeDevo.setUniformRowHeights(False)
        self.treeDevo.setItemsExpandable(False)
        self.treeDevo.setWordWrap(True)
        self.treeDevo.setHeaderHidden(True)
        self.treeDevo.setObjectName("treeDevo")
        self.treeDevo.header().setVisible(False)
        self.treeDevo.header().setCascadingSectionResizes(False)
        self.treeDevo.header().setHighlightSections(False)
        self.verticalLayout_10.addWidget(self.treeDevo)
        self.horizontalLayout_17.addWidget(self.boxSaidas_3)
        self.boxSaidas_4 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxSaidas_4.sizePolicy().hasHeightForWidth())
        self.boxSaidas_4.setSizePolicy(sizePolicy)
        self.boxSaidas_4.setMinimumSize(QtCore.QSize(0, 0))
        self.boxSaidas_4.setObjectName("boxSaidas_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.boxSaidas_4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.treeDevem = QtWidgets.QTreeWidget(self.boxSaidas_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeDevem.sizePolicy().hasHeightForWidth())
        self.treeDevem.setSizePolicy(sizePolicy)
        self.treeDevem.setMinimumSize(QtCore.QSize(300, 0))
        self.treeDevem.setAlternatingRowColors(True)
        self.treeDevem.setRootIsDecorated(True)
        self.treeDevem.setUniformRowHeights(False)
        self.treeDevem.setItemsExpandable(False)
        self.treeDevem.setWordWrap(True)
        self.treeDevem.setHeaderHidden(True)
        self.treeDevem.setObjectName("treeDevem")
        self.treeDevem.header().setVisible(False)
        self.treeDevem.header().setCascadingSectionResizes(False)
        self.treeDevem.header().setHighlightSections(False)
        self.verticalLayout_11.addWidget(self.treeDevem)
        self.horizontalLayout_17.addWidget(self.boxSaidas_4)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Adicionar Gasto"))
        self.labelValor.setText(_translate("Form", "Valor"))
        self.labelValor_2.setText(_translate("Form", "R$"))
        self.boxSaidas_3.setTitle(_translate("Form", "Eu devo..."))
        self.treeDevo.setSortingEnabled(True)
        self.treeDevo.headerItem().setText(0, _translate("Form", "Data"))
        self.treeDevo.headerItem().setText(1, _translate("Form", "Item"))
        self.treeDevo.headerItem().setText(2, _translate("Form", "Comentário"))
        self.treeDevo.headerItem().setText(3, _translate("Form", "Valor"))
        self.boxSaidas_4.setTitle(_translate("Form", "Me deve..."))
        self.treeDevem.setSortingEnabled(True)
        self.treeDevem.headerItem().setText(0, _translate("Form", "Data"))
        self.treeDevem.headerItem().setText(1, _translate("Form", "Item"))
        self.treeDevem.headerItem().setText(2, _translate("Form", "Comentário"))
        self.treeDevem.headerItem().setText(3, _translate("Form", "Valor"))

