# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dividir.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(664, 495)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.radioButtonDevem = QtWidgets.QRadioButton(self.frame)
        self.radioButtonDevem.setObjectName("radioButtonDevem")
        self.horizontalLayout_2.addWidget(self.radioButtonDevem)
        self.radioButtonDevo = QtWidgets.QRadioButton(self.frame)
        self.radioButtonDevo.setObjectName("radioButtonDevo")
        self.horizontalLayout_2.addWidget(self.radioButtonDevo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_6.addWidget(self.frame)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelMensagem = QtWidgets.QLabel(Form)
        self.labelMensagem.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMensagem.setObjectName("labelMensagem")
        self.verticalLayout.addWidget(self.labelMensagem)
        self.treeSaida = QtWidgets.QTreeWidget(Form)
        self.treeSaida.setAlternatingRowColors(True)
        self.treeSaida.setRootIsDecorated(True)
        self.treeSaida.setUniformRowHeights(False)
        self.treeSaida.setItemsExpandable(False)
        self.treeSaida.setWordWrap(True)
        self.treeSaida.setHeaderHidden(False)
        self.treeSaida.setObjectName("treeSaida")
        self.treeSaida.header().setVisible(True)
        self.treeSaida.header().setCascadingSectionResizes(False)
        self.treeSaida.header().setHighlightSections(False)
        self.verticalLayout.addWidget(self.treeSaida)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frameSemDividir = QtWidgets.QFrame(Form)
        self.frameSemDividir.setObjectName("frameSemDividir")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameSemDividir)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pessoasLabel = QtWidgets.QLabel(self.frameSemDividir)
        self.pessoasLabel.setObjectName("pessoasLabel")
        self.horizontalLayout_3.addWidget(self.pessoasLabel)
        self.spinPessoas = QtWidgets.QSpinBox(self.frameSemDividir)
        self.spinPessoas.setObjectName("spinPessoas")
        self.horizontalLayout_3.addWidget(self.spinPessoas)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_6.addWidget(self.frameSemDividir)
        self.frameDevo = QtWidgets.QFrame(Form)
        self.frameDevo.setObjectName("frameDevo")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frameDevo)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelDevo = QtWidgets.QLabel(self.frameDevo)
        self.labelDevo.setObjectName("labelDevo")
        self.horizontalLayout_4.addWidget(self.labelDevo)
        self.inputDevo = QtWidgets.QLineEdit(self.frameDevo)
        self.inputDevo.setObjectName("inputDevo")
        self.horizontalLayout_4.addWidget(self.inputDevo)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.umaParteEntreLabel = QtWidgets.QLabel(self.frameDevo)
        self.umaParteEntreLabel.setObjectName("umaParteEntreLabel")
        self.horizontalLayout_5.addWidget(self.umaParteEntreLabel)
        self.spinDevo = QtWidgets.QSpinBox(self.frameDevo)
        self.spinDevo.setObjectName("spinDevo")
        self.horizontalLayout_5.addWidget(self.spinDevo)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.label_2 = QtWidgets.QLabel(self.frameDevo)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        self.textEdit = QtWidgets.QTextEdit(self.frameDevo)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_8.addWidget(self.textEdit)
        self.horizontalLayout_6.addWidget(self.frameDevo)
        self.frameDeve = QtWidgets.QFrame(Form)
        self.frameDeve.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameDeve.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameDeve.setObjectName("frameDeve")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frameDeve)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frameDeve)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.inputDeve = QtWidgets.QLineEdit(self.frameDeve)
        self.inputDeve.setObjectName("inputDeve")
        self.horizontalLayout.addWidget(self.inputDeve)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.botaoAdicionar = QtWidgets.QPushButton(self.frameDeve)
        self.botaoAdicionar.setObjectName("botaoAdicionar")
        self.horizontalLayout_9.addWidget(self.botaoAdicionar)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.listDeve = QtWidgets.QListWidget(self.frameDeve)
        self.listDeve.setObjectName("listDeve")
        self.verticalLayout_7.addWidget(self.listDeve)
        self.label_3 = QtWidgets.QLabel(self.frameDeve)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.textEdit2 = QtWidgets.QTextEdit(self.frameDeve)
        self.textEdit2.setObjectName("textEdit2")
        self.verticalLayout_7.addWidget(self.textEdit2)
        self.horizontalLayout_6.addWidget(self.frameDeve)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelSoma = QtWidgets.QLabel(self.groupBox)
        self.labelSoma.setObjectName("labelSoma")
        self.verticalLayout_4.addWidget(self.labelSoma)
        self.verticalLayout_9.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelDividido = QtWidgets.QLabel(self.groupBox_2)
        self.labelDividido.setObjectName("labelDividido")
        self.verticalLayout_5.addWidget(self.labelDividido)
        self.verticalLayout_9.addWidget(self.groupBox_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_9)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_8.addWidget(self.pushButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Dividir"))
        self.radioButton.setText(_translate("Form", "Não criar dívida"))
        self.radioButtonDevem.setText(_translate("Form", "Devem para mim"))
        self.radioButtonDevo.setText(_translate("Form", "Eu devo para"))
        self.labelMensagem.setText(_translate("Form", "Selecione os itens para dividir"))
        self.treeSaida.setSortingEnabled(True)
        self.treeSaida.headerItem().setText(0, _translate("Form", "Data"))
        self.treeSaida.headerItem().setText(1, _translate("Form", "Item"))
        self.treeSaida.headerItem().setText(2, _translate("Form", "Valor"))
        self.pessoasLabel.setText(_translate("Form", "Pessoas:"))
        self.labelDevo.setText(_translate("Form", "Devo para:"))
        self.umaParteEntreLabel.setText(_translate("Form", "Uma parte entre:"))
        self.label_2.setText(_translate("Form", "Comentário"))
        self.label.setText(_translate("Form", "Nome:"))
        self.botaoAdicionar.setText(_translate("Form", "Adicionar"))
        self.label_3.setText(_translate("Form", "Comentário"))
        self.groupBox.setTitle(_translate("Form", "Soma:"))
        self.labelSoma.setText(_translate("Form", "TextLabel"))
        self.groupBox_2.setTitle(_translate("Form", "Dividido"))
        self.labelDividido.setText(_translate("Form", "TextLabel"))
        self.pushButton.setText(_translate("Form", "Dividir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

