# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dividir.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(656, 397)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelMensagem = QtWidgets.QLabel(Form)
        self.labelMensagem.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMensagem.setObjectName("labelMensagem")
        self.verticalLayout.addWidget(self.labelMensagem)
        self.treeSaida = QtWidgets.QTreeWidget(Form)
        self.treeSaida.setAlternatingRowColors(True)
        self.treeSaida.setRootIsDecorated(True)
        self.treeSaida.setUniformRowHeights(False)
        self.treeSaida.setItemsExpandable(False)
        self.treeSaida.setWordWrap(True)
        self.treeSaida.setHeaderHidden(False)
        self.treeSaida.setObjectName("treeSaida")
        self.treeSaida.header().setVisible(True)
        self.treeSaida.header().setCascadingSectionResizes(False)
        self.treeSaida.header().setHighlightSections(False)
        self.verticalLayout.addWidget(self.treeSaida)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pessoasLabel = QtWidgets.QLabel(Form)
        self.pessoasLabel.setObjectName("pessoasLabel")
        self.horizontalLayout_3.addWidget(self.pessoasLabel)
        self.spinPessoas = QtWidgets.QSpinBox(Form)
        self.spinPessoas.setObjectName("spinPessoas")
        self.horizontalLayout_3.addWidget(self.spinPessoas)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelSoma = QtWidgets.QLabel(self.groupBox)
        self.labelSoma.setObjectName("labelSoma")
        self.verticalLayout_4.addWidget(self.labelSoma)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelDividido = QtWidgets.QLabel(self.groupBox_2)
        self.labelDividido.setObjectName("labelDividido")
        self.verticalLayout_5.addWidget(self.labelDividido)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Dividir"))
        self.labelMensagem.setText(_translate("Form", "Selecione os itens para dividir"))
        self.treeSaida.setSortingEnabled(True)
        self.treeSaida.headerItem().setText(0, _translate("Form", "Data"))
        self.treeSaida.headerItem().setText(1, _translate("Form", "Item"))
        self.treeSaida.headerItem().setText(2, _translate("Form", "Valor"))
        self.pessoasLabel.setText(_translate("Form", "Pessoas:"))
        self.groupBox.setTitle(_translate("Form", "Soma:"))
        self.labelSoma.setText(_translate("Form", "TextLabel"))
        self.groupBox_2.setTitle(_translate("Form", "Dividido"))
        self.labelDividido.setText(_translate("Form", "TextLabel"))
        self.pushButton.setText(_translate("Form", "Dividir"))

