# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'entrada_add.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 181)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(9999, 9999))
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 481, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelEntrada = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelEntrada.setObjectName("labelEntrada")
        self.horizontalLayout.addWidget(self.labelEntrada)
        self.inputEntrada = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.inputEntrada.setObjectName("inputEntrada")
        self.horizontalLayout.addWidget(self.inputEntrada)
        self.labelValor = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelValor.setObjectName("labelValor")
        self.horizontalLayout.addWidget(self.labelValor)
        self.labelValor_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelValor_2.setObjectName("labelValor_2")
        self.horizontalLayout.addWidget(self.labelValor_2)
        self.spinValor = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.spinValor.setDecimals(2)
        self.spinValor.setMaximum(99999.99)
        self.spinValor.setProperty("value", 0.0)
        self.spinValor.setObjectName("spinValor")
        self.horizontalLayout.addWidget(self.spinValor)
        self.checkPago = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkPago.setObjectName("checkPago")
        self.horizontalLayout.addWidget(self.checkPago)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelPrevisao = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelPrevisao.setObjectName("labelPrevisao")
        self.horizontalLayout_2.addWidget(self.labelPrevisao)
        self.dateEdit = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_2.addWidget(self.dateEdit)
        self.botaoHoje = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.botaoHoje.setObjectName("botaoHoje")
        self.horizontalLayout_2.addWidget(self.botaoHoje)
        self.labelPago = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelPago.setEnabled(False)
        self.labelPago.setObjectName("labelPago")
        self.horizontalLayout_2.addWidget(self.labelPago)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.horizontalLayout_2.addWidget(self.dateEdit_2)
        self.botaoHoje_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.botaoHoje_2.setEnabled(False)
        self.botaoHoje_2.setObjectName("botaoHoje_2")
        self.horizontalLayout_2.addWidget(self.botaoHoje_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.labelComentario = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelComentario.setObjectName("labelComentario")
        self.verticalLayout.addWidget(self.labelComentario)
        self.textComentario = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textComentario.setObjectName("textComentario")
        self.verticalLayout.addWidget(self.textComentario)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.inputEntrada, self.spinValor)
        Form.setTabOrder(self.spinValor, self.textComentario)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Adicionar Entrada"))
        self.labelEntrada.setText(_translate("Form", "Entrada"))
        self.labelValor.setText(_translate("Form", "Valor"))
        self.labelValor_2.setText(_translate("Form", "R$"))
        self.checkPago.setText(_translate("Form", "Pago"))
        self.labelPrevisao.setText(_translate("Form", "Previsão"))
        self.botaoHoje.setText(_translate("Form", "Hoje"))
        self.labelPago.setText(_translate("Form", "Pago"))
        self.botaoHoje_2.setText(_translate("Form", "Hoje"))
        self.labelComentario.setText(_translate("Form", "Comentário"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

