# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gastos_add.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(690, 330)
        Form.setMinimumSize(QtCore.QSize(690, 330))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelGasto = QtWidgets.QLabel(Form)
        self.labelGasto.setObjectName("labelGasto")
        self.horizontalLayout.addWidget(self.labelGasto)
        self.inputGasto = QtWidgets.QLineEdit(Form)
        self.inputGasto.setObjectName("inputGasto")
        self.horizontalLayout.addWidget(self.inputGasto)
        self.labelValor = QtWidgets.QLabel(Form)
        self.labelValor.setObjectName("labelValor")
        self.horizontalLayout.addWidget(self.labelValor)
        self.labelValor_2 = QtWidgets.QLabel(Form)
        self.labelValor_2.setObjectName("labelValor_2")
        self.horizontalLayout.addWidget(self.labelValor_2)
        self.spinValor = QtWidgets.QDoubleSpinBox(Form)
        self.spinValor.setDecimals(2)
        self.spinValor.setMaximum(99999.99)
        self.spinValor.setProperty("value", 0.0)
        self.spinValor.setObjectName("spinValor")
        self.horizontalLayout.addWidget(self.spinValor)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelCategoria = QtWidgets.QLabel(Form)
        self.labelCategoria.setObjectName("labelCategoria")
        self.horizontalLayout_2.addWidget(self.labelCategoria)
        self.comboCategoria = QtWidgets.QComboBox(Form)
        self.comboCategoria.setObjectName("comboCategoria")
        self.horizontalLayout_2.addWidget(self.comboCategoria)
        self.labelSub = QtWidgets.QLabel(Form)
        self.labelSub.setObjectName("labelSub")
        self.horizontalLayout_2.addWidget(self.labelSub)
        self.comboSub = QtWidgets.QComboBox(Form)
        self.comboSub.setObjectName("comboSub")
        self.horizontalLayout_2.addWidget(self.comboSub)
        self.botaoAdd = QtWidgets.QPushButton(Form)
        self.botaoAdd.setObjectName("botaoAdd")
        self.horizontalLayout_2.addWidget(self.botaoAdd)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.treeWidget = QtWidgets.QTreeWidget(Form)
        self.treeWidget.setMinimumSize(QtCore.QSize(400, 0))
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.horizontalLayout_3.addWidget(self.treeWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupSoma = QtWidgets.QGroupBox(Form)
        self.groupSoma.setMinimumSize(QtCore.QSize(0, 40))
        self.groupSoma.setObjectName("groupSoma")
        self.labelSoma = QtWidgets.QLabel(self.groupSoma)
        self.labelSoma.setGeometry(QtCore.QRect(10, 20, 54, 17))
        self.labelSoma.setObjectName("labelSoma")
        self.verticalLayout.addWidget(self.groupSoma)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelData = QtWidgets.QLabel(Form)
        self.labelData.setObjectName("labelData")
        self.horizontalLayout_4.addWidget(self.labelData)
        self.dateEdit = QtWidgets.QDateEdit(Form)
        self.dateEdit.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_4.addWidget(self.dateEdit)
        self.botaoHoje = QtWidgets.QPushButton(Form)
        self.botaoHoje.setObjectName("botaoHoje")
        self.horizontalLayout_4.addWidget(self.botaoHoje)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.labelComentario = QtWidgets.QLabel(Form)
        self.labelComentario.setObjectName("labelComentario")
        self.verticalLayout.addWidget(self.labelComentario)
        self.textComentario = QtWidgets.QTextEdit(Form)
        self.textComentario.setObjectName("textComentario")
        self.verticalLayout.addWidget(self.textComentario)
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.inputGasto, self.spinValor)
        Form.setTabOrder(self.spinValor, self.comboCategoria)
        Form.setTabOrder(self.comboCategoria, self.comboSub)
        Form.setTabOrder(self.comboSub, self.botaoAdd)
        Form.setTabOrder(self.botaoAdd, self.dateEdit)
        Form.setTabOrder(self.dateEdit, self.textComentario)
        Form.setTabOrder(self.textComentario, self.treeWidget)
        Form.setTabOrder(self.treeWidget, self.botaoHoje)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Adicionar Gasto"))
        self.labelGasto.setText(_translate("Form", "Gasto"))
        self.labelGasto.setProperty("class", _translate("Form", "obrigatorio"))
        self.labelValor.setText(_translate("Form", "Valor"))
        self.labelValor_2.setText(_translate("Form", "R$"))
        self.labelCategoria.setText(_translate("Form", "Categoria"))
        self.labelSub.setText(_translate("Form", "Sub-categoria"))
        self.botaoAdd.setText(_translate("Form", "Adicionar na Lista"))
        self.treeWidget.headerItem().setText(0, _translate("Form", "Item"))
        self.treeWidget.headerItem().setText(1, _translate("Form", "Categoria"))
        self.treeWidget.headerItem().setText(2, _translate("Form", "Sub-Categoria"))
        self.treeWidget.headerItem().setText(3, _translate("Form", "Valor"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Form", "New Item"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("Form", "New Item"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("Form", "New Item"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("Form", "New Item"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("Form", "New Item"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("Form", "New Item"))
        self.treeWidget.topLevelItem(6).setText(0, _translate("Form", "New Item"))
        self.treeWidget.topLevelItem(7).setText(0, _translate("Form", "New Item"))
        self.treeWidget.topLevelItem(8).setText(0, _translate("Form", "New Item"))
        self.treeWidget.topLevelItem(9).setText(0, _translate("Form", "New Item"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.groupSoma.setTitle(_translate("Form", "Soma"))
        self.labelSoma.setText(_translate("Form", "0,00"))
        self.labelData.setText(_translate("Form", "Data"))
        self.botaoHoje.setText(_translate("Form", "Hoje"))
        self.labelComentario.setText(_translate("Form", "Comentário"))
        self.checkBox.setText(_translate("Form", "Dividir lista de gastos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

