# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gerador.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(906, 407)
        Form.setMinimumSize(QtCore.QSize(845, 400))
        Form.setMaximumSize(QtCore.QSize(9999, 9999))
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.boxGeralGastos = QtWidgets.QGroupBox(Form)
        self.boxGeralGastos.setMinimumSize(QtCore.QSize(600, 175))
        self.boxGeralGastos.setObjectName("boxGeralGastos")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.boxGeralGastos)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeGeralGastos = QtWidgets.QTreeWidget(self.boxGeralGastos)
        self.treeGeralGastos.setAlternatingRowColors(True)
        self.treeGeralGastos.setRootIsDecorated(True)
        self.treeGeralGastos.setUniformRowHeights(False)
        self.treeGeralGastos.setItemsExpandable(False)
        self.treeGeralGastos.setWordWrap(True)
        self.treeGeralGastos.setHeaderHidden(True)
        self.treeGeralGastos.setObjectName("treeGeralGastos")
        self.treeGeralGastos.header().setVisible(False)
        self.treeGeralGastos.header().setCascadingSectionResizes(False)
        self.treeGeralGastos.header().setHighlightSections(False)
        self.verticalLayout.addWidget(self.treeGeralGastos)
        self.verticalLayout_4.addWidget(self.boxGeralGastos)
        self.boxInvestimentos = QtWidgets.QGroupBox(Form)
        self.boxInvestimentos.setMinimumSize(QtCore.QSize(500, 175))
        self.boxInvestimentos.setObjectName("boxInvestimentos")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.boxInvestimentos)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeInvestimentos = QtWidgets.QTreeWidget(self.boxInvestimentos)
        self.treeInvestimentos.setAlternatingRowColors(True)
        self.treeInvestimentos.setRootIsDecorated(True)
        self.treeInvestimentos.setUniformRowHeights(False)
        self.treeInvestimentos.setItemsExpandable(False)
        self.treeInvestimentos.setWordWrap(True)
        self.treeInvestimentos.setHeaderHidden(True)
        self.treeInvestimentos.setObjectName("treeInvestimentos")
        self.treeInvestimentos.header().setVisible(False)
        self.treeInvestimentos.header().setCascadingSectionResizes(False)
        self.treeInvestimentos.header().setHighlightSections(False)
        self.verticalLayout_2.addWidget(self.treeInvestimentos)
        self.verticalLayout_4.addWidget(self.boxInvestimentos)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelGasto = QtWidgets.QLabel(Form)
        self.labelGasto.setObjectName("labelGasto")
        self.horizontalLayout.addWidget(self.labelGasto)
        self.inputGasto = QtWidgets.QLineEdit(Form)
        self.inputGasto.setObjectName("inputGasto")
        self.horizontalLayout.addWidget(self.inputGasto)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelValor = QtWidgets.QLabel(Form)
        self.labelValor.setObjectName("labelValor")
        self.horizontalLayout_4.addWidget(self.labelValor)
        self.labelValor_2 = QtWidgets.QLabel(Form)
        self.labelValor_2.setObjectName("labelValor_2")
        self.horizontalLayout_4.addWidget(self.labelValor_2)
        self.spinValor = QtWidgets.QDoubleSpinBox(Form)
        self.spinValor.setDecimals(2)
        self.spinValor.setMaximum(99999.99)
        self.spinValor.setProperty("value", 0.0)
        self.spinValor.setObjectName("spinValor")
        self.horizontalLayout_4.addWidget(self.spinValor)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelCategoria = QtWidgets.QLabel(Form)
        self.labelCategoria.setObjectName("labelCategoria")
        self.horizontalLayout_2.addWidget(self.labelCategoria)
        self.comboCategoria = QtWidgets.QComboBox(Form)
        self.comboCategoria.setObjectName("comboCategoria")
        self.horizontalLayout_2.addWidget(self.comboCategoria)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelSub = QtWidgets.QLabel(Form)
        self.labelSub.setObjectName("labelSub")
        self.horizontalLayout_5.addWidget(self.labelSub)
        self.comboSub = QtWidgets.QComboBox(Form)
        self.comboSub.setObjectName("comboSub")
        self.horizontalLayout_5.addWidget(self.comboSub)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelPrevisao = QtWidgets.QLabel(Form)
        self.labelPrevisao.setObjectName("labelPrevisao")
        self.horizontalLayout_3.addWidget(self.labelPrevisao)
        self.dateEdit = QtWidgets.QDateEdit(Form)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_3.addWidget(self.dateEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.labelComentario = QtWidgets.QLabel(Form)
        self.labelComentario.setObjectName("labelComentario")
        self.verticalLayout_3.addWidget(self.labelComentario)
        self.textComentario = QtWidgets.QTextEdit(Form)
        self.textComentario.setObjectName("textComentario")
        self.verticalLayout_3.addWidget(self.textComentario)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_5.addWidget(self.buttonBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Gerar um novo mês"))
        self.boxGeralGastos.setTitle(_translate("Form", "Gastos recorrentes - converte para gastos fixos"))
        self.treeGeralGastos.setSortingEnabled(True)
        self.treeGeralGastos.headerItem().setText(0, _translate("Form", "Nome"))
        self.treeGeralGastos.headerItem().setText(1, _translate("Form", "Valor"))
        self.treeGeralGastos.headerItem().setText(2, _translate("Form", "Vencimento"))
        self.treeGeralGastos.headerItem().setText(3, _translate("Form", "Prestação"))
        self.treeGeralGastos.headerItem().setText(4, _translate("Form", "Categoria"))
        self.treeGeralGastos.headerItem().setText(5, _translate("Form", "Sub-categoria"))
        self.boxInvestimentos.setTitle(_translate("Form", "Investimentos - converte para reservas"))
        self.treeInvestimentos.setSortingEnabled(True)
        self.treeInvestimentos.headerItem().setText(0, _translate("Form", "Nome"))
        self.treeInvestimentos.headerItem().setText(1, _translate("Form", "Valor"))
        self.labelGasto.setText(_translate("Form", "Nome"))
        self.labelValor.setText(_translate("Form", "Valor"))
        self.labelValor_2.setText(_translate("Form", "R$"))
        self.labelCategoria.setText(_translate("Form", "Categoria"))
        self.labelSub.setText(_translate("Form", "Sub-categoria"))
        self.labelPrevisao.setText(_translate("Form", "Vencimento"))
        self.labelComentario.setText(_translate("Form", "Comentário"))
        self.pushButton.setText(_translate("Form", "Salvar"))

