# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 600)
        Form.setMinimumSize(QtCore.QSize(1000, 600))
        Form.setMaximumSize(QtCore.QSize(1000, 600))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.Hoje = QtWidgets.QWidget()
        self.Hoje.setObjectName("Hoje")
        self.textBrowser = QtWidgets.QTextBrowser(self.Hoje)
        self.textBrowser.setGeometry(QtCore.QRect(150, 60, 161, 101))
        self.textBrowser.setObjectName("textBrowser")
        self.boxStatus = QtWidgets.QGroupBox(self.Hoje)
        self.boxStatus.setGeometry(QtCore.QRect(360, 10, 391, 241))
        self.boxStatus.setObjectName("boxStatus")
        self.frameSoma = QtWidgets.QFrame(self.boxStatus)
        self.frameSoma.setGeometry(QtCore.QRect(10, 40, 181, 41))
        self.frameSoma.setStyleSheet("")
        self.frameSoma.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSoma.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSoma.setObjectName("frameSoma")
        self.labelSoma = QtWidgets.QLabel(self.frameSoma)
        self.labelSoma.setGeometry(QtCore.QRect(13, 10, 71, 20))
        self.labelSoma.setObjectName("labelSoma")
        self.labelVSoma = QtWidgets.QLabel(self.frameSoma)
        self.labelVSoma.setGeometry(QtCore.QRect(90, 10, 51, 21))
        self.labelVSoma.setObjectName("labelVSoma")
        self.frameEntrada = QtWidgets.QFrame(self.boxStatus)
        self.frameEntrada.setGeometry(QtCore.QRect(10, 90, 181, 41))
        self.frameEntrada.setStyleSheet("")
        self.frameEntrada.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameEntrada.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameEntrada.setObjectName("frameEntrada")
        self.labelEntrada = QtWidgets.QLabel(self.frameEntrada)
        self.labelEntrada.setGeometry(QtCore.QRect(13, 10, 71, 20))
        self.labelEntrada.setObjectName("labelEntrada")
        self.labelVEntrada = QtWidgets.QLabel(self.frameEntrada)
        self.labelVEntrada.setGeometry(QtCore.QRect(70, 10, 71, 21))
        self.labelVEntrada.setObjectName("labelVEntrada")
        self.frameSoma_3 = QtWidgets.QFrame(self.boxStatus)
        self.frameSoma_3.setGeometry(QtCore.QRect(200, 80, 181, 41))
        self.frameSoma_3.setStyleSheet("")
        self.frameSoma_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSoma_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSoma_3.setObjectName("frameSoma_3")
        self.labelSoma_3 = QtWidgets.QLabel(self.frameSoma_3)
        self.labelSoma_3.setGeometry(QtCore.QRect(13, 10, 91, 20))
        self.labelSoma_3.setObjectName("labelSoma_3")
        self.labelVSoma_3 = QtWidgets.QLabel(self.frameSoma_3)
        self.labelVSoma_3.setGeometry(QtCore.QRect(100, 10, 51, 21))
        self.labelVSoma_3.setObjectName("labelVSoma_3")
        self.frameSoma_2 = QtWidgets.QFrame(self.boxStatus)
        self.frameSoma_2.setGeometry(QtCore.QRect(200, 40, 181, 41))
        self.frameSoma_2.setStyleSheet("")
        self.frameSoma_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSoma_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSoma_2.setObjectName("frameSoma_2")
        self.labelSoma_2 = QtWidgets.QLabel(self.frameSoma_2)
        self.labelSoma_2.setGeometry(QtCore.QRect(13, 10, 81, 20))
        self.labelSoma_2.setObjectName("labelSoma_2")
        self.labelVSoma_2 = QtWidgets.QLabel(self.frameSoma_2)
        self.labelVSoma_2.setGeometry(QtCore.QRect(100, 10, 51, 21))
        self.labelVSoma_2.setObjectName("labelVSoma_2")
        self.frameSoma_4 = QtWidgets.QFrame(self.boxStatus)
        self.frameSoma_4.setGeometry(QtCore.QRect(200, 120, 181, 41))
        self.frameSoma_4.setStyleSheet("")
        self.frameSoma_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSoma_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSoma_4.setObjectName("frameSoma_4")
        self.labelSoma_4 = QtWidgets.QLabel(self.frameSoma_4)
        self.labelSoma_4.setGeometry(QtCore.QRect(13, 10, 91, 20))
        self.labelSoma_4.setObjectName("labelSoma_4")
        self.labelVSoma_4 = QtWidgets.QLabel(self.frameSoma_4)
        self.labelVSoma_4.setGeometry(QtCore.QRect(70, 10, 51, 21))
        self.labelVSoma_4.setObjectName("labelVSoma_4")
        self.botaoGasto = QtWidgets.QPushButton(self.Hoje)
        self.botaoGasto.setGeometry(QtCore.QRect(30, 20, 80, 25))
        self.botaoGasto.setObjectName("botaoGasto")
        self.stackedWidget = QtWidgets.QStackedWidget(self.Hoje)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(260, 240, 651, 291))
        self.stackedWidget.setMouseTracking(False)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageGastos = QtWidgets.QWidget()
        self.pageGastos.setObjectName("pageGastos")
        self.boxGastos = QtWidgets.QGroupBox(self.pageGastos)
        self.boxGastos.setGeometry(QtCore.QRect(0, 0, 651, 291))
        self.boxGastos.setObjectName("boxGastos")
        self.treeSaida = QtWidgets.QTreeWidget(self.boxGastos)
        self.treeSaida.setGeometry(QtCore.QRect(0, 20, 651, 271))
        self.treeSaida.setAlternatingRowColors(True)
        self.treeSaida.setRootIsDecorated(True)
        self.treeSaida.setUniformRowHeights(False)
        self.treeSaida.setItemsExpandable(False)
        self.treeSaida.setWordWrap(True)
        self.treeSaida.setHeaderHidden(True)
        self.treeSaida.setObjectName("treeSaida")
        self.treeSaida.header().setVisible(False)
        self.treeSaida.header().setCascadingSectionResizes(False)
        self.treeSaida.header().setHighlightSections(False)
        self.stackedWidget.addWidget(self.pageGastos)
        self.pageEntrada = QtWidgets.QWidget()
        self.pageEntrada.setObjectName("pageEntrada")
        self.boxEntrada = QtWidgets.QGroupBox(self.pageEntrada)
        self.boxEntrada.setGeometry(QtCore.QRect(0, 0, 651, 291))
        self.boxEntrada.setObjectName("boxEntrada")
        self.treeEntrada = QtWidgets.QTreeWidget(self.boxEntrada)
        self.treeEntrada.setGeometry(QtCore.QRect(0, 20, 651, 271))
        self.treeEntrada.setAlternatingRowColors(True)
        self.treeEntrada.setWordWrap(True)
        self.treeEntrada.setObjectName("treeEntrada")
        self.treeEntrada.header().setVisible(False)
        self.stackedWidget.addWidget(self.pageEntrada)
        self.pageFixo = QtWidgets.QWidget()
        self.pageFixo.setObjectName("pageFixo")
        self.boxFixo = QtWidgets.QGroupBox(self.pageFixo)
        self.boxFixo.setGeometry(QtCore.QRect(0, 0, 651, 291))
        self.boxFixo.setObjectName("boxFixo")
        self.treeFixo = QtWidgets.QTreeWidget(self.boxFixo)
        self.treeFixo.setGeometry(QtCore.QRect(0, 20, 651, 271))
        self.treeFixo.setAlternatingRowColors(True)
        self.treeFixo.setRootIsDecorated(True)
        self.treeFixo.setUniformRowHeights(False)
        self.treeFixo.setItemsExpandable(False)
        self.treeFixo.setWordWrap(True)
        self.treeFixo.setHeaderHidden(True)
        self.treeFixo.setObjectName("treeFixo")
        self.treeFixo.header().setVisible(False)
        self.treeFixo.header().setCascadingSectionResizes(False)
        self.treeFixo.header().setHighlightSections(False)
        self.stackedWidget.addWidget(self.pageFixo)
        self.pageReserva = QtWidgets.QWidget()
        self.pageReserva.setObjectName("pageReserva")
        self.boxSaidas_2 = QtWidgets.QGroupBox(self.pageReserva)
        self.boxSaidas_2.setGeometry(QtCore.QRect(10, 10, 641, 281))
        self.boxSaidas_2.setObjectName("boxSaidas_2")
        self.stackedWidget.addWidget(self.pageReserva)
        self.botaoEntrada = QtWidgets.QPushButton(self.Hoje)
        self.botaoEntrada.setGeometry(QtCore.QRect(30, 50, 91, 25))
        self.botaoEntrada.setObjectName("botaoEntrada")
        self.botaoFixo = QtWidgets.QPushButton(self.Hoje)
        self.botaoFixo.setGeometry(QtCore.QRect(30, 80, 91, 25))
        self.botaoFixo.setObjectName("botaoFixo")
        self.botaoReserva = QtWidgets.QPushButton(self.Hoje)
        self.botaoReserva.setGeometry(QtCore.QRect(30, 120, 91, 25))
        self.botaoReserva.setObjectName("botaoReserva")
        self.listMenu = QtWidgets.QListWidget(self.Hoje)
        self.listMenu.setGeometry(QtCore.QRect(20, 280, 191, 192))
        self.listMenu.setObjectName("listMenu")
        item = QtWidgets.QListWidgetItem()
        self.listMenu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listMenu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listMenu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listMenu.addItem(item)
        self.tabWidget.addTab(self.Hoje, "")
        self.Geral = QtWidgets.QWidget()
        self.Geral.setObjectName("Geral")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.Geral)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 10, 301, 141))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.tabWidget.addTab(self.Geral, "")
        self.Dividas = QtWidgets.QWidget()
        self.Dividas.setObjectName("Dividas")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.Dividas)
        self.textBrowser_3.setGeometry(QtCore.QRect(10, 10, 256, 111))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.tabWidget.addTab(self.Dividas, "")
        self.Config = QtWidgets.QWidget()
        self.Config.setObjectName("Config")
        self.boxConfig = QtWidgets.QGroupBox(self.Config)
        self.boxConfig.setGeometry(QtCore.QRect(50, 30, 881, 171))
        self.boxConfig.setObjectName("boxConfig")
        self.boxCategorias = QtWidgets.QGroupBox(self.Config)
        self.boxCategorias.setGeometry(QtCore.QRect(90, 230, 381, 241))
        self.boxCategorias.setObjectName("boxCategorias")
        self.treeCategorias = QtWidgets.QTreeWidget(self.boxCategorias)
        self.treeCategorias.setGeometry(QtCore.QRect(0, 20, 381, 221))
        self.treeCategorias.setAlternatingRowColors(True)
        self.treeCategorias.setObjectName("treeCategorias")
        self.treeCategorias.header().setVisible(False)
        self.boxPessoas = QtWidgets.QGroupBox(self.Config)
        self.boxPessoas.setGeometry(QtCore.QRect(510, 230, 380, 241))
        self.boxPessoas.setObjectName("boxPessoas")
        self.treePessoas = QtWidgets.QTreeWidget(self.boxPessoas)
        self.treePessoas.setGeometry(QtCore.QRect(0, 20, 380, 221))
        self.treePessoas.setAlternatingRowColors(True)
        self.treePessoas.setObjectName("treePessoas")
        self.treePessoas.header().setVisible(False)
        self.treePessoas.header().setDefaultSectionSize(100)
        self.botaoCategoriaAdicionar = QtWidgets.QPushButton(self.Config)
        self.botaoCategoriaAdicionar.setGeometry(QtCore.QRect(140, 480, 131, 25))
        self.botaoCategoriaAdicionar.setObjectName("botaoCategoriaAdicionar")
        self.botaoPessoaAdicionar = QtWidgets.QPushButton(self.Config)
        self.botaoPessoaAdicionar.setGeometry(QtCore.QRect(560, 490, 111, 25))
        self.botaoPessoaAdicionar.setObjectName("botaoPessoaAdicionar")
        self.botaoCategoriaEditar = QtWidgets.QPushButton(self.Config)
        self.botaoCategoriaEditar.setGeometry(QtCore.QRect(330, 490, 80, 31))
        self.botaoCategoriaEditar.setObjectName("botaoCategoriaEditar")
        self.botaoPessoaEditar = QtWidgets.QPushButton(self.Config)
        self.botaoPessoaEditar.setGeometry(QtCore.QRect(750, 490, 80, 25))
        self.botaoPessoaEditar.setObjectName("botaoPessoaEditar")
        self.botaoSubAdicionar = QtWidgets.QPushButton(self.Config)
        self.botaoSubAdicionar.setGeometry(QtCore.QRect(130, 510, 151, 25))
        self.botaoSubAdicionar.setObjectName("botaoSubAdicionar")
        self.tabWidget.addTab(self.Config, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Controle de Gastos"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">adição de gastos em lista</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">adição de gastos em limbo</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">informações mais essenciais</p></body></html>"))
        self.boxStatus.setTitle(_translate("Form", "Status"))
        self.labelSoma.setText(_translate("Form", "Total Gasto:"))
        self.labelVSoma.setText(_translate("Form", "{}"))
        self.labelEntrada.setText(_translate("Form", "Entrada:"))
        self.labelVEntrada.setText(_translate("Form", "{}"))
        self.labelSoma_3.setText(_translate("Form", "Saída do mês:"))
        self.labelVSoma_3.setText(_translate("Form", "{}"))
        self.labelSoma_2.setText(_translate("Form", "Gasto diário:"))
        self.labelVSoma_2.setText(_translate("Form", "{}"))
        self.labelSoma_4.setText(_translate("Form", "Reserva:"))
        self.labelVSoma_4.setText(_translate("Form", "{}"))
        self.botaoGasto.setText(_translate("Form", "Novo Gasto"))
        self.boxGastos.setTitle(_translate("Form", "Gastos"))
        self.treeSaida.setSortingEnabled(True)
        self.treeSaida.headerItem().setText(0, _translate("Form", "Data"))
        self.treeSaida.headerItem().setText(1, _translate("Form", "Item"))
        self.treeSaida.headerItem().setText(2, _translate("Form", "Categoria"))
        self.treeSaida.headerItem().setText(3, _translate("Form", "Sub-categoria"))
        self.treeSaida.headerItem().setText(4, _translate("Form", "Valor"))
        self.boxEntrada.setTitle(_translate("Form", "Entrada"))
        self.treeEntrada.setSortingEnabled(True)
        self.treeEntrada.headerItem().setText(0, _translate("Form", "Item"))
        self.treeEntrada.headerItem().setText(1, _translate("Form", "Previsão"))
        self.treeEntrada.headerItem().setText(2, _translate("Form", "Data"))
        self.treeEntrada.headerItem().setText(3, _translate("Form", "Valor"))
        self.boxFixo.setTitle(_translate("Form", "Saídas do Mês"))
        self.treeFixo.setSortingEnabled(True)
        self.treeFixo.headerItem().setText(0, _translate("Form", "Data"))
        self.treeFixo.headerItem().setText(1, _translate("Form", "Item"))
        self.treeFixo.headerItem().setText(2, _translate("Form", "Categoria"))
        self.treeFixo.headerItem().setText(3, _translate("Form", "Sub-categoria"))
        self.treeFixo.headerItem().setText(4, _translate("Form", "Valor"))
        self.boxSaidas_2.setTitle(_translate("Form", "Reserva"))
        self.botaoEntrada.setText(_translate("Form", "Nova Entrada"))
        self.botaoFixo.setText(_translate("Form", "Novo Fixo"))
        self.botaoReserva.setText(_translate("Form", "Nova Reserva"))
        __sortingEnabled = self.listMenu.isSortingEnabled()
        self.listMenu.setSortingEnabled(False)
        item = self.listMenu.item(0)
        item.setText(_translate("Form", "Gastos"))
        item = self.listMenu.item(1)
        item.setText(_translate("Form", "Entrada"))
        item = self.listMenu.item(2)
        item.setText(_translate("Form", "Fixo"))
        item = self.listMenu.item(3)
        item.setText(_translate("Form", "Reserva"))
        self.listMenu.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Hoje), _translate("Form", "Hoje"))
        self.textBrowser_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Lista e cadastro dos gastos gerais (mensais e etc)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    Padrão de gastos (percentuais)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Lista dos investimentos</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Informações do ano</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Geração de relatórios</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Geral), _translate("Form", "Geral"))
        self.textBrowser_3.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Lista de dívidas</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    O que eu devo</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    O que me devem</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Dividas), _translate("Form", "Dívidas"))
        self.boxConfig.setTitle(_translate("Form", "Configurações"))
        self.boxCategorias.setTitle(_translate("Form", "Categorias"))
        self.treeCategorias.headerItem().setText(0, _translate("Form", "nome"))
        self.treeCategorias.headerItem().setText(1, _translate("Form", "status"))
        self.boxPessoas.setTitle(_translate("Form", "Pessoas"))
        self.treePessoas.headerItem().setText(0, _translate("Form", "nome"))
        self.treePessoas.headerItem().setText(1, _translate("Form", "status"))
        self.botaoCategoriaAdicionar.setText(_translate("Form", "Adicionar Categoria"))
        self.botaoPessoaAdicionar.setText(_translate("Form", "Adicionar Pessoa"))
        self.botaoCategoriaEditar.setText(_translate("Form", "Editar"))
        self.botaoPessoaEditar.setText(_translate("Form", "Editar"))
        self.botaoSubAdicionar.setText(_translate("Form", "Adicionar Sub-Categoria"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Config), _translate("Form", "Configurações"))

