# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1260, 604)
        Form.setMinimumSize(QtCore.QSize(1250, 600))
        Form.setMaximumSize(QtCore.QSize(9999, 9999))
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Hoje = QtWidgets.QWidget()
        self.Hoje.setObjectName("Hoje")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Hoje)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolAdicionar = QtWidgets.QToolButton(self.Hoje)
        self.toolAdicionar.setMinimumSize(QtCore.QSize(100, 50))
        self.toolAdicionar.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.toolAdicionar.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolAdicionar.setAutoRaise(True)
        self.toolAdicionar.setArrowType(QtCore.Qt.DownArrow)
        self.toolAdicionar.setObjectName("toolAdicionar")
        self.horizontalLayout.addWidget(self.toolAdicionar)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.boxMedia = QtWidgets.QGroupBox(self.Hoje)
        self.boxMedia.setAlignment(QtCore.Qt.AlignCenter)
        self.boxMedia.setObjectName("boxMedia")
        self.labelMedia = QtWidgets.QLabel(self.boxMedia)
        self.labelMedia.setGeometry(QtCore.QRect(0, 20, 121, 20))
        self.labelMedia.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMedia.setObjectName("labelMedia")
        self.verticalLayout_3.addWidget(self.boxMedia)
        self.boxLimiteDia = QtWidgets.QGroupBox(self.Hoje)
        self.boxLimiteDia.setAlignment(QtCore.Qt.AlignCenter)
        self.boxLimiteDia.setObjectName("boxLimiteDia")
        self.labelLimiteDia = QtWidgets.QLabel(self.boxLimiteDia)
        self.labelLimiteDia.setGeometry(QtCore.QRect(0, 20, 121, 20))
        self.labelLimiteDia.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLimiteDia.setObjectName("labelLimiteDia")
        self.verticalLayout_3.addWidget(self.boxLimiteDia)
        self.boxAjuste = QtWidgets.QGroupBox(self.Hoje)
        self.boxAjuste.setAlignment(QtCore.Qt.AlignCenter)
        self.boxAjuste.setObjectName("boxAjuste")
        self.labelAjuste = QtWidgets.QLabel(self.boxAjuste)
        self.labelAjuste.setGeometry(QtCore.QRect(0, 20, 121, 51))
        self.labelAjuste.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelAjuste.setObjectName("labelAjuste")
        self.verticalLayout_3.addWidget(self.boxAjuste)
        spacerItem1 = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_15.addLayout(self.verticalLayout_3)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupDia = QtWidgets.QGroupBox(self.Hoje)
        self.groupDia.setMinimumSize(QtCore.QSize(400, 50))
        self.groupDia.setMaximumSize(QtCore.QSize(16777215, 75))
        self.groupDia.setObjectName("groupDia")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupDia)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.labelTotalAjustes = QtWidgets.QLabel(self.groupDia)
        self.labelTotalAjustes.setObjectName("labelTotalAjustes")
        self.horizontalLayout_14.addWidget(self.labelTotalAjustes)
        self.labelTotalAjustesV = QtWidgets.QLabel(self.groupDia)
        self.labelTotalAjustesV.setObjectName("labelTotalAjustesV")
        self.horizontalLayout_14.addWidget(self.labelTotalAjustesV)
        self.labelTotalEntrada = QtWidgets.QLabel(self.groupDia)
        self.labelTotalEntrada.setObjectName("labelTotalEntrada")
        self.horizontalLayout_14.addWidget(self.labelTotalEntrada)
        self.labelTotalEntradaV = QtWidgets.QLabel(self.groupDia)
        self.labelTotalEntradaV.setObjectName("labelTotalEntradaV")
        self.horizontalLayout_14.addWidget(self.labelTotalEntradaV)
        self.labelTotalFixo = QtWidgets.QLabel(self.groupDia)
        self.labelTotalFixo.setObjectName("labelTotalFixo")
        self.horizontalLayout_14.addWidget(self.labelTotalFixo)
        self.labelTotalFixoV = QtWidgets.QLabel(self.groupDia)
        self.labelTotalFixoV.setObjectName("labelTotalFixoV")
        self.horizontalLayout_14.addWidget(self.labelTotalFixoV)
        self.labelTotalReserva = QtWidgets.QLabel(self.groupDia)
        self.labelTotalReserva.setObjectName("labelTotalReserva")
        self.horizontalLayout_14.addWidget(self.labelTotalReserva)
        self.labelTotalReservaV = QtWidgets.QLabel(self.groupDia)
        self.labelTotalReservaV.setObjectName("labelTotalReservaV")
        self.horizontalLayout_14.addWidget(self.labelTotalReservaV)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.verticalLayout_8.addWidget(self.groupDia)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.groupBox = QtWidgets.QGroupBox(self.Hoje)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelHojeGasto = QtWidgets.QLabel(self.groupBox)
        self.labelHojeGasto.setObjectName("labelHojeGasto")
        self.horizontalLayout_4.addWidget(self.labelHojeGasto)
        self.labelHojeGastoV = QtWidgets.QLabel(self.groupBox)
        self.labelHojeGastoV.setObjectName("labelHojeGastoV")
        self.horizontalLayout_4.addWidget(self.labelHojeGastoV)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelHojeLimite = QtWidgets.QLabel(self.groupBox)
        self.labelHojeLimite.setObjectName("labelHojeLimite")
        self.horizontalLayout_5.addWidget(self.labelHojeLimite)
        self.labelHojeLimiteV = QtWidgets.QLabel(self.groupBox)
        self.labelHojeLimiteV.setObjectName("labelHojeLimiteV")
        self.horizontalLayout_5.addWidget(self.labelHojeLimiteV)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelHojeResto = QtWidgets.QLabel(self.groupBox)
        self.labelHojeResto.setObjectName("labelHojeResto")
        self.horizontalLayout_6.addWidget(self.labelHojeResto)
        self.labelHojeRestaV = QtWidgets.QLabel(self.groupBox)
        self.labelHojeRestaV.setObjectName("labelHojeRestaV")
        self.horizontalLayout_6.addWidget(self.labelHojeRestaV)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.progressBarHoje = QtWidgets.QProgressBar(self.groupBox)
        self.progressBarHoje.setMaximum(100)
        self.progressBarHoje.setProperty("value", 24)
        self.progressBarHoje.setObjectName("progressBarHoje")
        self.verticalLayout_4.addWidget(self.progressBarHoje)
        self.horizontalLayout_13.addWidget(self.groupBox)
        self.groupBox1 = QtWidgets.QGroupBox(self.Hoje)
        self.groupBox1.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox1.setObjectName("groupBox1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelSemanaGasto = QtWidgets.QLabel(self.groupBox1)
        self.labelSemanaGasto.setObjectName("labelSemanaGasto")
        self.horizontalLayout_7.addWidget(self.labelSemanaGasto)
        self.labelSemanaGastoV = QtWidgets.QLabel(self.groupBox1)
        self.labelSemanaGastoV.setObjectName("labelSemanaGastoV")
        self.horizontalLayout_7.addWidget(self.labelSemanaGastoV)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelSemanaLimite = QtWidgets.QLabel(self.groupBox1)
        self.labelSemanaLimite.setObjectName("labelSemanaLimite")
        self.horizontalLayout_8.addWidget(self.labelSemanaLimite)
        self.labelSemanaLimiteV = QtWidgets.QLabel(self.groupBox1)
        self.labelSemanaLimiteV.setObjectName("labelSemanaLimiteV")
        self.horizontalLayout_8.addWidget(self.labelSemanaLimiteV)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.labelSemanaResta = QtWidgets.QLabel(self.groupBox1)
        self.labelSemanaResta.setObjectName("labelSemanaResta")
        self.horizontalLayout_9.addWidget(self.labelSemanaResta)
        self.labelSemanaRestaV = QtWidgets.QLabel(self.groupBox1)
        self.labelSemanaRestaV.setObjectName("labelSemanaRestaV")
        self.horizontalLayout_9.addWidget(self.labelSemanaRestaV)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.progressBarSemana = QtWidgets.QProgressBar(self.groupBox1)
        self.progressBarSemana.setMaximum(100)
        self.progressBarSemana.setProperty("value", 24)
        self.progressBarSemana.setObjectName("progressBarSemana")
        self.verticalLayout_5.addWidget(self.progressBarSemana)
        self.horizontalLayout_13.addWidget(self.groupBox1)
        self.groupBox2 = QtWidgets.QGroupBox(self.Hoje)
        self.groupBox2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox2.setObjectName("groupBox2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.labelMesGasto = QtWidgets.QLabel(self.groupBox2)
        self.labelMesGasto.setObjectName("labelMesGasto")
        self.horizontalLayout_10.addWidget(self.labelMesGasto)
        self.labelMesGastoV = QtWidgets.QLabel(self.groupBox2)
        self.labelMesGastoV.setObjectName("labelMesGastoV")
        self.horizontalLayout_10.addWidget(self.labelMesGastoV)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.labelMesLimite = QtWidgets.QLabel(self.groupBox2)
        self.labelMesLimite.setObjectName("labelMesLimite")
        self.horizontalLayout_11.addWidget(self.labelMesLimite)
        self.labelMesLimiteV = QtWidgets.QLabel(self.groupBox2)
        self.labelMesLimiteV.setObjectName("labelMesLimiteV")
        self.horizontalLayout_11.addWidget(self.labelMesLimiteV)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.labelMesResta = QtWidgets.QLabel(self.groupBox2)
        self.labelMesResta.setObjectName("labelMesResta")
        self.horizontalLayout_12.addWidget(self.labelMesResta)
        self.labelMesRestaV = QtWidgets.QLabel(self.groupBox2)
        self.labelMesRestaV.setObjectName("labelMesRestaV")
        self.horizontalLayout_12.addWidget(self.labelMesRestaV)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.progressBarMes = QtWidgets.QProgressBar(self.groupBox2)
        self.progressBarMes.setProperty("value", 24)
        self.progressBarMes.setObjectName("progressBarMes")
        self.verticalLayout_6.addWidget(self.progressBarMes)
        self.horizontalLayout_13.addWidget(self.groupBox2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_15.addLayout(self.verticalLayout_8)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.frame_2 = QtWidgets.QFrame(self.Hoje)
        self.frame_2.setMinimumSize(QtCore.QSize(630, 290))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(110, 0, 511, 291))
        self.stackedWidget.setMouseTracking(False)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageGastos = QtWidgets.QWidget()
        self.pageGastos.setObjectName("pageGastos")
        self.boxGastos = QtWidgets.QGroupBox(self.pageGastos)
        self.boxGastos.setGeometry(QtCore.QRect(0, 0, 511, 291))
        self.boxGastos.setObjectName("boxGastos")
        self.treeSaida = QtWidgets.QTreeWidget(self.boxGastos)
        self.treeSaida.setGeometry(QtCore.QRect(0, 20, 511, 271))
        self.treeSaida.setAlternatingRowColors(True)
        self.treeSaida.setRootIsDecorated(True)
        self.treeSaida.setUniformRowHeights(False)
        self.treeSaida.setItemsExpandable(False)
        self.treeSaida.setWordWrap(True)
        self.treeSaida.setHeaderHidden(True)
        self.treeSaida.setObjectName("treeSaida")
        self.treeSaida.header().setVisible(False)
        self.treeSaida.header().setCascadingSectionResizes(False)
        self.treeSaida.header().setHighlightSections(False)
        self.stackedWidget.addWidget(self.pageGastos)
        self.pageEntrada = QtWidgets.QWidget()
        self.pageEntrada.setObjectName("pageEntrada")
        self.boxEntrada = QtWidgets.QGroupBox(self.pageEntrada)
        self.boxEntrada.setGeometry(QtCore.QRect(0, 0, 511, 291))
        self.boxEntrada.setObjectName("boxEntrada")
        self.treeEntrada = QtWidgets.QTreeWidget(self.boxEntrada)
        self.treeEntrada.setGeometry(QtCore.QRect(0, 20, 511, 271))
        self.treeEntrada.setAlternatingRowColors(True)
        self.treeEntrada.setWordWrap(True)
        self.treeEntrada.setObjectName("treeEntrada")
        self.treeEntrada.header().setVisible(False)
        self.stackedWidget.addWidget(self.pageEntrada)
        self.pageFixo = QtWidgets.QWidget()
        self.pageFixo.setObjectName("pageFixo")
        self.boxFixo = QtWidgets.QGroupBox(self.pageFixo)
        self.boxFixo.setGeometry(QtCore.QRect(0, 0, 511, 291))
        self.boxFixo.setObjectName("boxFixo")
        self.treeFixo = QtWidgets.QTreeWidget(self.boxFixo)
        self.treeFixo.setGeometry(QtCore.QRect(0, 20, 511, 271))
        self.treeFixo.setAlternatingRowColors(True)
        self.treeFixo.setRootIsDecorated(True)
        self.treeFixo.setUniformRowHeights(False)
        self.treeFixo.setItemsExpandable(False)
        self.treeFixo.setWordWrap(True)
        self.treeFixo.setHeaderHidden(True)
        self.treeFixo.setObjectName("treeFixo")
        self.treeFixo.header().setVisible(False)
        self.treeFixo.header().setCascadingSectionResizes(False)
        self.treeFixo.header().setHighlightSections(False)
        self.stackedWidget.addWidget(self.pageFixo)
        self.pageReserva = QtWidgets.QWidget()
        self.pageReserva.setObjectName("pageReserva")
        self.boxSaidas_2 = QtWidgets.QGroupBox(self.pageReserva)
        self.boxSaidas_2.setGeometry(QtCore.QRect(0, 0, 521, 291))
        self.boxSaidas_2.setObjectName("boxSaidas_2")
        self.treeReserva = QtWidgets.QTreeWidget(self.boxSaidas_2)
        self.treeReserva.setGeometry(QtCore.QRect(0, 20, 511, 271))
        self.treeReserva.setAlternatingRowColors(True)
        self.treeReserva.setRootIsDecorated(True)
        self.treeReserva.setUniformRowHeights(False)
        self.treeReserva.setItemsExpandable(False)
        self.treeReserva.setWordWrap(True)
        self.treeReserva.setHeaderHidden(True)
        self.treeReserva.setObjectName("treeReserva")
        self.treeReserva.header().setVisible(False)
        self.treeReserva.header().setCascadingSectionResizes(False)
        self.treeReserva.header().setHighlightSections(False)
        self.stackedWidget.addWidget(self.pageReserva)
        self.listMenu = QtWidgets.QListWidget(self.frame_2)
        self.listMenu.setGeometry(QtCore.QRect(50, 20, 71, 151))
        self.listMenu.setAlternatingRowColors(False)
        self.listMenu.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.listMenu.setProperty("isWrapping", True)
        self.listMenu.setObjectName("listMenu")
        item = QtWidgets.QListWidgetItem()
        self.listMenu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listMenu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listMenu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listMenu.addItem(item)
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 200, 91, 89))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.botaoAjustes = QtWidgets.QPushButton(self.layoutWidget)
        self.botaoAjustes.setObjectName("botaoAjustes")
        self.verticalLayout_9.addWidget(self.botaoAjustes)
        self.botaoDividir = QtWidgets.QPushButton(self.layoutWidget)
        self.botaoDividir.setObjectName("botaoDividir")
        self.verticalLayout_9.addWidget(self.botaoDividir)
        self.botaoExcluir = QtWidgets.QPushButton(self.layoutWidget)
        self.botaoExcluir.setObjectName("botaoExcluir")
        self.verticalLayout_9.addWidget(self.botaoExcluir)
        self.layoutWidget.raise_()
        self.listMenu.raise_()
        self.stackedWidget.raise_()
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        self.comboGrafico = QtWidgets.QComboBox(self.Hoje)
        self.comboGrafico.setObjectName("comboGrafico")
        self.comboGrafico.addItem("")
        self.comboGrafico.addItem("")
        self.comboGrafico.addItem("")
        self.gridLayout_2.addWidget(self.comboGrafico, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 0, 1, 1)
        self.botaoAjuste = QtWidgets.QPushButton(self.Hoje)
        self.botaoAjuste.setObjectName("botaoAjuste")
        self.gridLayout_2.addWidget(self.botaoAjuste, 0, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.graficoPizza = PlotPizza(self.Hoje)
        self.graficoPizza.setMinimumSize(QtCore.QSize(400, 250))
        self.graficoPizza.setObjectName("graficoPizza")
        self.verticalLayout_2.addWidget(self.graficoPizza)
        self.graficoBarra = PlotBarra(self.Hoje)
        self.graficoBarra.setMinimumSize(QtCore.QSize(400, 250))
        self.graficoBarra.setObjectName("graficoBarra")
        self.verticalLayout_2.addWidget(self.graficoBarra)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.Hoje, "")
        self.Geral = QtWidgets.QWidget()
        self.Geral.setObjectName("Geral")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.Geral)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem4)
        self.botaoConverter = QtWidgets.QPushButton(self.Geral)
        self.botaoConverter.setObjectName("botaoConverter")
        self.horizontalLayout_25.addWidget(self.botaoConverter)
        self.verticalLayout_27.addLayout(self.horizontalLayout_25)
        self.boxGeralGastos = QtWidgets.QGroupBox(self.Geral)
        self.boxGeralGastos.setObjectName("boxGeralGastos")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.boxGeralGastos)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem5)
        self.botaoNovoRecorrente = QtWidgets.QPushButton(self.boxGeralGastos)
        self.botaoNovoRecorrente.setObjectName("botaoNovoRecorrente")
        self.horizontalLayout_23.addWidget(self.botaoNovoRecorrente)
        self.verticalLayout_25.addLayout(self.horizontalLayout_23)
        self.treeGeralGastos = QtWidgets.QTreeWidget(self.boxGeralGastos)
        self.treeGeralGastos.setAlternatingRowColors(True)
        self.treeGeralGastos.setRootIsDecorated(True)
        self.treeGeralGastos.setUniformRowHeights(False)
        self.treeGeralGastos.setItemsExpandable(False)
        self.treeGeralGastos.setWordWrap(True)
        self.treeGeralGastos.setHeaderHidden(True)
        self.treeGeralGastos.setObjectName("treeGeralGastos")
        self.treeGeralGastos.header().setVisible(False)
        self.treeGeralGastos.header().setCascadingSectionResizes(False)
        self.treeGeralGastos.header().setHighlightSections(False)
        self.verticalLayout_25.addWidget(self.treeGeralGastos)
        self.verticalLayout_27.addWidget(self.boxGeralGastos)
        self.boxInvestimentos = QtWidgets.QGroupBox(self.Geral)
        self.boxInvestimentos.setObjectName("boxInvestimentos")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.boxInvestimentos)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem6)
        self.botaoNovoInvestimento = QtWidgets.QPushButton(self.boxInvestimentos)
        self.botaoNovoInvestimento.setObjectName("botaoNovoInvestimento")
        self.horizontalLayout_24.addWidget(self.botaoNovoInvestimento)
        self.verticalLayout_26.addLayout(self.horizontalLayout_24)
        self.treeInvestimentos = QtWidgets.QTreeWidget(self.boxInvestimentos)
        self.treeInvestimentos.setAlternatingRowColors(True)
        self.treeInvestimentos.setRootIsDecorated(True)
        self.treeInvestimentos.setUniformRowHeights(False)
        self.treeInvestimentos.setItemsExpandable(False)
        self.treeInvestimentos.setWordWrap(True)
        self.treeInvestimentos.setHeaderHidden(True)
        self.treeInvestimentos.setObjectName("treeInvestimentos")
        self.treeInvestimentos.header().setVisible(False)
        self.treeInvestimentos.header().setCascadingSectionResizes(False)
        self.treeInvestimentos.header().setHighlightSections(False)
        self.verticalLayout_26.addWidget(self.treeInvestimentos)
        self.verticalLayout_27.addWidget(self.boxInvestimentos)
        self.horizontalLayout_26.addLayout(self.verticalLayout_27)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.boxFiltro = QtWidgets.QGroupBox(self.Geral)
        self.boxFiltro.setObjectName("boxFiltro")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.boxFiltro)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkRelSub = QtWidgets.QCheckBox(self.boxFiltro)
        self.checkRelSub.setObjectName("checkRelSub")
        self.gridLayout_3.addWidget(self.checkRelSub, 0, 3, 1, 1)
        self.checkRelFim = QtWidgets.QCheckBox(self.boxFiltro)
        self.checkRelFim.setObjectName("checkRelFim")
        self.gridLayout_3.addWidget(self.checkRelFim, 0, 5, 1, 1)
        self.comboCategoria = QtWidgets.QComboBox(self.boxFiltro)
        self.comboCategoria.setObjectName("comboCategoria")
        self.gridLayout_3.addWidget(self.comboCategoria, 1, 2, 1, 1)
        self.dateFim = QtWidgets.QDateEdit(self.boxFiltro)
        self.dateFim.setCalendarPopup(True)
        self.dateFim.setObjectName("dateFim")
        self.gridLayout_3.addWidget(self.dateFim, 1, 5, 1, 1)
        self.checkRelCat = QtWidgets.QCheckBox(self.boxFiltro)
        self.checkRelCat.setObjectName("checkRelCat")
        self.gridLayout_3.addWidget(self.checkRelCat, 0, 2, 1, 1)
        self.checkRelInicio = QtWidgets.QCheckBox(self.boxFiltro)
        self.checkRelInicio.setObjectName("checkRelInicio")
        self.gridLayout_3.addWidget(self.checkRelInicio, 0, 4, 1, 1)
        self.comboSub = QtWidgets.QComboBox(self.boxFiltro)
        self.comboSub.setObjectName("comboSub")
        self.gridLayout_3.addWidget(self.comboSub, 1, 3, 1, 1)
        self.inputFiltro = QtWidgets.QLineEdit(self.boxFiltro)
        self.inputFiltro.setObjectName("inputFiltro")
        self.gridLayout_3.addWidget(self.inputFiltro, 1, 1, 1, 1)
        self.dateInicio = QtWidgets.QDateEdit(self.boxFiltro)
        self.dateInicio.setCalendarPopup(True)
        self.dateInicio.setObjectName("dateInicio")
        self.gridLayout_3.addWidget(self.dateInicio, 1, 4, 1, 1)
        self.checkRelTipo = QtWidgets.QCheckBox(self.boxFiltro)
        self.checkRelTipo.setObjectName("checkRelTipo")
        self.gridLayout_3.addWidget(self.checkRelTipo, 0, 0, 1, 1)
        self.comboTipo = QtWidgets.QComboBox(self.boxFiltro)
        self.comboTipo.setObjectName("comboTipo")
        self.comboTipo.addItem("")
        self.comboTipo.addItem("")
        self.comboTipo.addItem("")
        self.gridLayout_3.addWidget(self.comboTipo, 1, 0, 1, 1)
        self.checkRelNome = QtWidgets.QCheckBox(self.boxFiltro)
        self.checkRelNome.setObjectName("checkRelNome")
        self.gridLayout_3.addWidget(self.checkRelNome, 0, 1, 1, 1)
        self.botaoFiltro = QtWidgets.QPushButton(self.boxFiltro)
        self.botaoFiltro.setObjectName("botaoFiltro")
        self.gridLayout_3.addWidget(self.botaoFiltro, 1, 6, 1, 1)
        self.botaoLimpa = QtWidgets.QPushButton(self.boxFiltro)
        self.botaoLimpa.setObjectName("botaoLimpa")
        self.gridLayout_3.addWidget(self.botaoLimpa, 0, 6, 1, 1)
        self.verticalLayout_22.addLayout(self.gridLayout_3)
        self.treeFiltro = QtWidgets.QTreeWidget(self.boxFiltro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeFiltro.sizePolicy().hasHeightForWidth())
        self.treeFiltro.setSizePolicy(sizePolicy)
        self.treeFiltro.setMinimumSize(QtCore.QSize(661, 100))
        self.treeFiltro.setAlternatingRowColors(True)
        self.treeFiltro.setRootIsDecorated(True)
        self.treeFiltro.setUniformRowHeights(False)
        self.treeFiltro.setItemsExpandable(False)
        self.treeFiltro.setWordWrap(True)
        self.treeFiltro.setHeaderHidden(True)
        self.treeFiltro.setObjectName("treeFiltro")
        self.treeFiltro.header().setVisible(False)
        self.treeFiltro.header().setCascadingSectionResizes(False)
        self.treeFiltro.header().setHighlightSections(False)
        self.verticalLayout_22.addWidget(self.treeFiltro)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem7)
        self.label = QtWidgets.QLabel(self.boxFiltro)
        self.label.setObjectName("label")
        self.horizontalLayout_21.addWidget(self.label)
        self.labelSomaFiltro = QtWidgets.QLabel(self.boxFiltro)
        self.labelSomaFiltro.setObjectName("labelSomaFiltro")
        self.horizontalLayout_21.addWidget(self.labelSomaFiltro)
        self.verticalLayout_22.addLayout(self.horizontalLayout_21)
        self.verticalLayout_24.addWidget(self.boxFiltro)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.treeAno = QtWidgets.QTreeWidget(self.Geral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeAno.sizePolicy().hasHeightForWidth())
        self.treeAno.setSizePolicy(sizePolicy)
        self.treeAno.setMinimumSize(QtCore.QSize(211, 221))
        self.treeAno.setMaximumSize(QtCore.QSize(1750, 16777215))
        self.treeAno.setObjectName("treeAno")
        self.treeAno.header().setVisible(False)
        self.horizontalLayout_22.addWidget(self.treeAno)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.graficoLinha = PlotLinha(self.Geral)
        self.graficoLinha.setMinimumSize(QtCore.QSize(460, 210))
        self.graficoLinha.setObjectName("graficoLinha")
        self.verticalLayout_23.addWidget(self.graficoLinha)
        self.frame = QtWidgets.QFrame(self.Geral)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelRelatorio = QtWidgets.QLabel(self.frame)
        self.labelRelatorio.setObjectName("labelRelatorio")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelRelatorio)
        self.comboRelatorio = QtWidgets.QComboBox(self.frame)
        self.comboRelatorio.setObjectName("comboRelatorio")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboRelatorio)
        self.horizontalLayout_16.addLayout(self.formLayout)
        self.botaoRelatorio = QtWidgets.QPushButton(self.frame)
        self.botaoRelatorio.setObjectName("botaoRelatorio")
        self.horizontalLayout_16.addWidget(self.botaoRelatorio)
        self.verticalLayout_23.addWidget(self.frame)
        self.horizontalLayout_22.addLayout(self.verticalLayout_23)
        self.verticalLayout_24.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_26.addLayout(self.verticalLayout_24)
        self.tabWidget.addTab(self.Geral, "")
        self.Dividas = QtWidgets.QWidget()
        self.Dividas.setObjectName("Dividas")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.Dividas)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.Dvidas = QtWidgets.QGroupBox(self.Dividas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Dvidas.sizePolicy().hasHeightForWidth())
        self.Dvidas.setSizePolicy(sizePolicy)
        self.Dvidas.setObjectName("Dvidas")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.Dvidas)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.groupBox3 = QtWidgets.QGroupBox(self.Dvidas)
        self.groupBox3.setObjectName("groupBox3")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.groupBox3)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.botaoDividaNova = QtWidgets.QPushButton(self.groupBox3)
        self.botaoDividaNova.setObjectName("botaoDividaNova")
        self.verticalLayout_15.addWidget(self.botaoDividaNova)
        self.botaoDividaPagar = QtWidgets.QPushButton(self.groupBox3)
        self.botaoDividaPagar.setObjectName("botaoDividaPagar")
        self.verticalLayout_15.addWidget(self.botaoDividaPagar)
        self.horizontalLayout_18.addLayout(self.verticalLayout_15)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.botaoDividaUnificar = QtWidgets.QPushButton(self.groupBox3)
        self.botaoDividaUnificar.setObjectName("botaoDividaUnificar")
        self.verticalLayout_18.addWidget(self.botaoDividaUnificar)
        self.pushButton = QtWidgets.QPushButton(self.groupBox3)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_18.addWidget(self.pushButton)
        self.horizontalLayout_18.addLayout(self.verticalLayout_18)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem8)
        self.boxMedia_2 = QtWidgets.QGroupBox(self.groupBox3)
        self.boxMedia_2.setMinimumSize(QtCore.QSize(0, 50))
        self.boxMedia_2.setAlignment(QtCore.Qt.AlignCenter)
        self.boxMedia_2.setObjectName("boxMedia_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.boxMedia_2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.labelDevo = QtWidgets.QLabel(self.boxMedia_2)
        self.labelDevo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDevo.setObjectName("labelDevo")
        self.verticalLayout_12.addWidget(self.labelDevo)
        self.horizontalLayout_18.addWidget(self.boxMedia_2)
        self.boxLimiteDia_2 = QtWidgets.QGroupBox(self.groupBox3)
        self.boxLimiteDia_2.setMinimumSize(QtCore.QSize(0, 50))
        self.boxLimiteDia_2.setAlignment(QtCore.Qt.AlignCenter)
        self.boxLimiteDia_2.setObjectName("boxLimiteDia_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.boxLimiteDia_2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.labelDevem = QtWidgets.QLabel(self.boxLimiteDia_2)
        self.labelDevem.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDevem.setObjectName("labelDevem")
        self.verticalLayout_13.addWidget(self.labelDevem)
        self.horizontalLayout_18.addWidget(self.boxLimiteDia_2)
        self.boxAjuste_2 = QtWidgets.QGroupBox(self.groupBox3)
        self.boxAjuste_2.setMinimumSize(QtCore.QSize(0, 50))
        self.boxAjuste_2.setAlignment(QtCore.Qt.AlignCenter)
        self.boxAjuste_2.setObjectName("boxAjuste_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.boxAjuste_2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.labelGeral = QtWidgets.QLabel(self.boxAjuste_2)
        self.labelGeral.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGeral.setObjectName("labelGeral")
        self.verticalLayout_14.addWidget(self.labelGeral)
        self.horizontalLayout_18.addWidget(self.boxAjuste_2)
        self.horizontalLayout_19.addWidget(self.groupBox3)
        self.verticalLayout_16.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.boxSaidas_3 = QtWidgets.QGroupBox(self.Dvidas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxSaidas_3.sizePolicy().hasHeightForWidth())
        self.boxSaidas_3.setSizePolicy(sizePolicy)
        self.boxSaidas_3.setMinimumSize(QtCore.QSize(0, 0))
        self.boxSaidas_3.setObjectName("boxSaidas_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.boxSaidas_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.treeDevo = QtWidgets.QTreeWidget(self.boxSaidas_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeDevo.sizePolicy().hasHeightForWidth())
        self.treeDevo.setSizePolicy(sizePolicy)
        self.treeDevo.setMinimumSize(QtCore.QSize(300, 0))
        self.treeDevo.setAlternatingRowColors(True)
        self.treeDevo.setRootIsDecorated(True)
        self.treeDevo.setUniformRowHeights(False)
        self.treeDevo.setItemsExpandable(False)
        self.treeDevo.setWordWrap(True)
        self.treeDevo.setHeaderHidden(True)
        self.treeDevo.setObjectName("treeDevo")
        self.treeDevo.header().setVisible(False)
        self.treeDevo.header().setCascadingSectionResizes(False)
        self.treeDevo.header().setHighlightSections(False)
        self.verticalLayout_10.addWidget(self.treeDevo)
        self.horizontalLayout_17.addWidget(self.boxSaidas_3)
        self.boxSaidas_4 = QtWidgets.QGroupBox(self.Dvidas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxSaidas_4.sizePolicy().hasHeightForWidth())
        self.boxSaidas_4.setSizePolicy(sizePolicy)
        self.boxSaidas_4.setMinimumSize(QtCore.QSize(0, 0))
        self.boxSaidas_4.setObjectName("boxSaidas_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.boxSaidas_4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.treeDevem = QtWidgets.QTreeWidget(self.boxSaidas_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeDevem.sizePolicy().hasHeightForWidth())
        self.treeDevem.setSizePolicy(sizePolicy)
        self.treeDevem.setMinimumSize(QtCore.QSize(300, 0))
        self.treeDevem.setAlternatingRowColors(True)
        self.treeDevem.setRootIsDecorated(True)
        self.treeDevem.setUniformRowHeights(False)
        self.treeDevem.setItemsExpandable(False)
        self.treeDevem.setWordWrap(True)
        self.treeDevem.setHeaderHidden(True)
        self.treeDevem.setObjectName("treeDevem")
        self.treeDevem.header().setVisible(False)
        self.treeDevem.header().setCascadingSectionResizes(False)
        self.treeDevem.header().setHighlightSections(False)
        self.verticalLayout_11.addWidget(self.treeDevem)
        self.horizontalLayout_17.addWidget(self.boxSaidas_4)
        self.verticalLayout_16.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_28.addWidget(self.Dvidas)
        self.boxCategorias = QtWidgets.QGroupBox(self.Dividas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxCategorias.sizePolicy().hasHeightForWidth())
        self.boxCategorias.setSizePolicy(sizePolicy)
        self.boxCategorias.setMinimumSize(QtCore.QSize(300, 0))
        self.boxCategorias.setObjectName("boxCategorias")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.boxCategorias)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.treeCategorias = QtWidgets.QTreeWidget(self.boxCategorias)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeCategorias.sizePolicy().hasHeightForWidth())
        self.treeCategorias.setSizePolicy(sizePolicy)
        self.treeCategorias.setMinimumSize(QtCore.QSize(400, 0))
        self.treeCategorias.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.treeCategorias.setAlternatingRowColors(True)
        self.treeCategorias.setObjectName("treeCategorias")
        self.treeCategorias.header().setVisible(False)
        self.verticalLayout_17.addWidget(self.treeCategorias)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem9)
        self.botaoCategoriaAdicionar = QtWidgets.QPushButton(self.boxCategorias)
        self.botaoCategoriaAdicionar.setObjectName("botaoCategoriaAdicionar")
        self.horizontalLayout_20.addWidget(self.botaoCategoriaAdicionar)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem10)
        self.botaoSubAdicionar = QtWidgets.QPushButton(self.boxCategorias)
        self.botaoSubAdicionar.setObjectName("botaoSubAdicionar")
        self.horizontalLayout_20.addWidget(self.botaoSubAdicionar)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem11)
        self.verticalLayout_17.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_28.addWidget(self.boxCategorias)
        self.tabWidget.addTab(self.Dividas, "")
        self.horizontalLayout_27.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(2)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Controle de Gastos"))
        self.toolAdicionar.setAccessibleName(_translate("Form", "tool"))
        self.toolAdicionar.setText(_translate("Form", "Adicionar"))
        self.boxMedia.setAccessibleName(_translate("Form", "quadro"))
        self.boxMedia.setTitle(_translate("Form", "Média por dia"))
        self.labelMedia.setText(_translate("Form", "R$100,00"))
        self.boxLimiteDia.setAccessibleName(_translate("Form", "quadro"))
        self.boxLimiteDia.setTitle(_translate("Form", "Limite por dia"))
        self.labelLimiteDia.setText(_translate("Form", "R$100,00"))
        self.boxAjuste.setAccessibleName(_translate("Form", "quadro"))
        self.boxAjuste.setTitle(_translate("Form", "{ajuste}"))
        self.labelAjuste.setText(_translate("Form", "R$100,00"))
        self.groupDia.setTitle(_translate("Form", "Dia: 02 de 28 (07%)"))
        self.labelTotalAjustes.setText(_translate("Form", "Ajustes:"))
        self.labelTotalAjustesV.setText(_translate("Form", "R$1000,00"))
        self.labelTotalEntrada.setText(_translate("Form", "Entrada:"))
        self.labelTotalEntradaV.setText(_translate("Form", "R$1000,00"))
        self.labelTotalFixo.setText(_translate("Form", "Gastos Fixos:"))
        self.labelTotalFixoV.setText(_translate("Form", "R$1000,00"))
        self.labelTotalReserva.setText(_translate("Form", "Reserva:"))
        self.labelTotalReservaV.setText(_translate("Form", "R$1000,00"))
        self.groupBox.setTitle(_translate("Form", "Diário"))
        self.labelHojeGasto.setText(_translate("Form", "Gasto:"))
        self.labelHojeGastoV.setText(_translate("Form", "R$1000,00"))
        self.labelHojeLimite.setText(_translate("Form", "Limite:"))
        self.labelHojeLimiteV.setText(_translate("Form", "R$1000,00"))
        self.labelHojeResto.setText(_translate("Form", "Resta:"))
        self.labelHojeRestaV.setText(_translate("Form", "R$1000,00"))
        self.groupBox1.setTitle(_translate("Form", "Semanal"))
        self.labelSemanaGasto.setText(_translate("Form", "Gasto:"))
        self.labelSemanaGastoV.setText(_translate("Form", "R$1000,00"))
        self.labelSemanaLimite.setText(_translate("Form", "Limite:"))
        self.labelSemanaLimiteV.setText(_translate("Form", "R$1000,00"))
        self.labelSemanaResta.setText(_translate("Form", "Resta:"))
        self.labelSemanaRestaV.setText(_translate("Form", "R$1000,00"))
        self.groupBox2.setTitle(_translate("Form", "Mensal"))
        self.labelMesGasto.setText(_translate("Form", "Gasto:"))
        self.labelMesGastoV.setText(_translate("Form", "R$1000,00"))
        self.labelMesLimite.setText(_translate("Form", "Limite:"))
        self.labelMesLimiteV.setText(_translate("Form", "R$1000,00"))
        self.labelMesResta.setText(_translate("Form", "Resta:"))
        self.labelMesRestaV.setText(_translate("Form", "R$1000,00"))
        self.boxGastos.setTitle(_translate("Form", "Gastos"))
        self.treeSaida.setSortingEnabled(True)
        self.treeSaida.headerItem().setText(0, _translate("Form", "Data"))
        self.treeSaida.headerItem().setText(1, _translate("Form", "Item"))
        self.treeSaida.headerItem().setText(2, _translate("Form", "Categoria"))
        self.treeSaida.headerItem().setText(3, _translate("Form", "Sub-categoria"))
        self.treeSaida.headerItem().setText(4, _translate("Form", "Valor"))
        self.boxEntrada.setTitle(_translate("Form", "Entrada"))
        self.treeEntrada.setSortingEnabled(True)
        self.treeEntrada.headerItem().setText(0, _translate("Form", "Item"))
        self.treeEntrada.headerItem().setText(1, _translate("Form", "Previsão"))
        self.treeEntrada.headerItem().setText(2, _translate("Form", "Data"))
        self.treeEntrada.headerItem().setText(3, _translate("Form", "Valor"))
        self.boxFixo.setTitle(_translate("Form", "Saídas do Mês"))
        self.treeFixo.setSortingEnabled(True)
        self.treeFixo.headerItem().setText(0, _translate("Form", "Item"))
        self.treeFixo.headerItem().setText(1, _translate("Form", "Vencimento"))
        self.treeFixo.headerItem().setText(2, _translate("Form", "Pago"))
        self.treeFixo.headerItem().setText(3, _translate("Form", "Categoria"))
        self.treeFixo.headerItem().setText(4, _translate("Form", "Sub-categoria"))
        self.treeFixo.headerItem().setText(5, _translate("Form", "Valor"))
        self.boxSaidas_2.setTitle(_translate("Form", "Reserva"))
        self.treeReserva.setSortingEnabled(True)
        self.treeReserva.headerItem().setText(0, _translate("Form", "Item"))
        self.treeReserva.headerItem().setText(1, _translate("Form", "Valor"))
        self.treeReserva.headerItem().setText(2, _translate("Form", "Comentário"))
        self.listMenu.setAccessibleName(_translate("Form", "selecao"))
        __sortingEnabled = self.listMenu.isSortingEnabled()
        self.listMenu.setSortingEnabled(False)
        item = self.listMenu.item(0)
        item.setText(_translate("Form", "Gastos"))
        item = self.listMenu.item(1)
        item.setText(_translate("Form", "Entrada"))
        item = self.listMenu.item(2)
        item.setText(_translate("Form", "Fixo"))
        item = self.listMenu.item(3)
        item.setText(_translate("Form", "Reserva"))
        self.listMenu.setSortingEnabled(__sortingEnabled)
        self.botaoAjustes.setText(_translate("Form", "Ajustes"))
        self.botaoDividir.setText(_translate("Form", "Dividir"))
        self.botaoExcluir.setText(_translate("Form", "Excluir"))
        self.comboGrafico.setItemText(0, _translate("Form", "Gastos"))
        self.comboGrafico.setItemText(1, _translate("Form", "Fixos"))
        self.comboGrafico.setItemText(2, _translate("Form", "Total"))
        self.botaoAjuste.setText(_translate("Form", "Calibrar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Hoje), _translate("Form", "Hoje"))
        self.botaoConverter.setText(_translate("Form", "Converter"))
        self.boxGeralGastos.setTitle(_translate("Form", "Gastos recorrentes"))
        self.botaoNovoRecorrente.setText(_translate("Form", "Novo"))
        self.treeGeralGastos.setSortingEnabled(True)
        self.treeGeralGastos.headerItem().setText(0, _translate("Form", "Nome"))
        self.treeGeralGastos.headerItem().setText(1, _translate("Form", "Tipo"))
        self.treeGeralGastos.headerItem().setText(2, _translate("Form", "Valor"))
        self.treeGeralGastos.headerItem().setText(3, _translate("Form", "Vencimento"))
        self.treeGeralGastos.headerItem().setText(4, _translate("Form", "Prestação"))
        self.treeGeralGastos.headerItem().setText(5, _translate("Form", "Categoria"))
        self.treeGeralGastos.headerItem().setText(6, _translate("Form", "Sub-categoria"))
        self.boxInvestimentos.setTitle(_translate("Form", "Investimentos"))
        self.botaoNovoInvestimento.setText(_translate("Form", "Novo"))
        self.treeInvestimentos.setSortingEnabled(True)
        self.treeInvestimentos.headerItem().setText(0, _translate("Form", "Nome"))
        self.treeInvestimentos.headerItem().setText(1, _translate("Form", "Valor"))
        self.boxFiltro.setTitle(_translate("Form", "Filtro"))
        self.checkRelSub.setText(_translate("Form", "Sub-categoria"))
        self.checkRelFim.setText(_translate("Form", "Fim"))
        self.checkRelCat.setText(_translate("Form", "Categoria"))
        self.checkRelInicio.setText(_translate("Form", "Início"))
        self.checkRelTipo.setText(_translate("Form", "Tipo"))
        self.comboTipo.setItemText(0, _translate("Form", "gasto"))
        self.comboTipo.setItemText(1, _translate("Form", "entrada"))
        self.comboTipo.setItemText(2, _translate("Form", "fixo"))
        self.checkRelNome.setText(_translate("Form", "Nome"))
        self.botaoFiltro.setText(_translate("Form", "Filtro"))
        self.botaoLimpa.setText(_translate("Form", "Limpa"))
        self.treeFiltro.setSortingEnabled(True)
        self.treeFiltro.headerItem().setText(0, _translate("Form", "Tipo"))
        self.treeFiltro.headerItem().setText(1, _translate("Form", "Item"))
        self.treeFiltro.headerItem().setText(2, _translate("Form", "Data"))
        self.treeFiltro.headerItem().setText(3, _translate("Form", "Categoria"))
        self.treeFiltro.headerItem().setText(4, _translate("Form", "Sub-categoria"))
        self.treeFiltro.headerItem().setText(5, _translate("Form", "Valor"))
        self.treeFiltro.headerItem().setText(6, _translate("Form", "Comentários"))
        self.label.setText(_translate("Form", "Soma: "))
        self.labelSomaFiltro.setText(_translate("Form", "R$0,00"))
        self.treeAno.headerItem().setText(0, _translate("Form", "Mês"))
        self.treeAno.headerItem().setText(1, _translate("Form", "Entrada"))
        self.treeAno.headerItem().setText(2, _translate("Form", "Saída"))
        self.labelRelatorio.setText(_translate("Form", "Gerar relatório de:"))
        self.botaoRelatorio.setText(_translate("Form", "gerar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Geral), _translate("Form", "Geral"))
        self.Dvidas.setTitle(_translate("Form", "Dívidas"))
        self.groupBox3.setTitle(_translate("Form", "Soma"))
        self.botaoDividaNova.setText(_translate("Form", "Nova Dívida"))
        self.botaoDividaPagar.setText(_translate("Form", "Pagar Dívida"))
        self.botaoDividaUnificar.setText(_translate("Form", "Unificar Dívida"))
        self.pushButton.setText(_translate("Form", "Relatório"))
        self.boxMedia_2.setAccessibleName(_translate("Form", "quadro"))
        self.boxMedia_2.setTitle(_translate("Form", "Eu devo..."))
        self.labelDevo.setText(_translate("Form", "R$100,00"))
        self.boxLimiteDia_2.setAccessibleName(_translate("Form", "quadro"))
        self.boxLimiteDia_2.setTitle(_translate("Form", "Me devem..."))
        self.labelDevem.setText(_translate("Form", "R$100,00"))
        self.boxAjuste_2.setAccessibleName(_translate("Form", "quadro"))
        self.boxAjuste_2.setTitle(_translate("Form", "Geral"))
        self.labelGeral.setText(_translate("Form", "R$100,00"))
        self.boxSaidas_3.setTitle(_translate("Form", "Eu devo..."))
        self.treeDevo.setSortingEnabled(True)
        self.treeDevo.headerItem().setText(0, _translate("Form", "Data"))
        self.treeDevo.headerItem().setText(1, _translate("Form", "Item"))
        self.treeDevo.headerItem().setText(2, _translate("Form", "Comentário"))
        self.treeDevo.headerItem().setText(3, _translate("Form", "Valor"))
        self.boxSaidas_4.setTitle(_translate("Form", "Me deve..."))
        self.treeDevem.setSortingEnabled(True)
        self.treeDevem.headerItem().setText(0, _translate("Form", "Data"))
        self.treeDevem.headerItem().setText(1, _translate("Form", "Item"))
        self.treeDevem.headerItem().setText(2, _translate("Form", "Comentário"))
        self.treeDevem.headerItem().setText(3, _translate("Form", "Valor"))
        self.boxCategorias.setTitle(_translate("Form", "Categorias"))
        self.treeCategorias.headerItem().setText(0, _translate("Form", "nome"))
        self.treeCategorias.headerItem().setText(1, _translate("Form", "status"))
        self.botaoCategoriaAdicionar.setText(_translate("Form", "Adicionar Categoria"))
        self.botaoSubAdicionar.setText(_translate("Form", "Adicionar Sub-Categoria"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Dividas), _translate("Form", "Outros"))

from ui.plotcanvas import PlotBarra, PlotLinha, PlotPizza
