# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1259, 600)
        Form.setMinimumSize(QtCore.QSize(1000, 600))
        Form.setMaximumSize(QtCore.QSize(10000, 600))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.Hoje = QtWidgets.QWidget()
        self.Hoje.setObjectName("Hoje")
        self.boxStatus = QtWidgets.QFrame(self.Hoje)
        self.boxStatus.setGeometry(QtCore.QRect(120, 0, 561, 231))
        self.boxStatus.setObjectName("boxStatus")
        self.frame = QtWidgets.QFrame(self.boxStatus)
        self.frame.setGeometry(QtCore.QRect(10, 80, 531, 141))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.boxHoje = QtWidgets.QGroupBox(self.frame)
        self.boxHoje.setGeometry(QtCore.QRect(30, 0, 141, 131))
        self.boxHoje.setStyleSheet("")
        self.boxHoje.setObjectName("boxHoje")
        self.frameHojeGasto = QtWidgets.QFrame(self.boxHoje)
        self.frameHojeGasto.setGeometry(QtCore.QRect(10, 30, 121, 21))
        self.frameHojeGasto.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameHojeGasto.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameHojeGasto.setObjectName("frameHojeGasto")
        self.labelHojeGasto = QtWidgets.QLabel(self.frameHojeGasto)
        self.labelHojeGasto.setGeometry(QtCore.QRect(0, 0, 54, 17))
        self.labelHojeGasto.setObjectName("labelHojeGasto")
        self.labelHojeGastoV = QtWidgets.QLabel(self.frameHojeGasto)
        self.labelHojeGastoV.setGeometry(QtCore.QRect(50, 0, 71, 17))
        self.labelHojeGastoV.setObjectName("labelHojeGastoV")
        self.frameHojeLimite = QtWidgets.QFrame(self.boxHoje)
        self.frameHojeLimite.setGeometry(QtCore.QRect(10, 50, 121, 21))
        self.frameHojeLimite.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameHojeLimite.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameHojeLimite.setObjectName("frameHojeLimite")
        self.labelHojeLimite = QtWidgets.QLabel(self.frameHojeLimite)
        self.labelHojeLimite.setGeometry(QtCore.QRect(0, 0, 54, 17))
        self.labelHojeLimite.setObjectName("labelHojeLimite")
        self.labelHojeLimiteV = QtWidgets.QLabel(self.frameHojeLimite)
        self.labelHojeLimiteV.setGeometry(QtCore.QRect(50, 0, 71, 17))
        self.labelHojeLimiteV.setObjectName("labelHojeLimiteV")
        self.frameHojeResto = QtWidgets.QFrame(self.boxHoje)
        self.frameHojeResto.setGeometry(QtCore.QRect(10, 70, 121, 21))
        self.frameHojeResto.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameHojeResto.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameHojeResto.setObjectName("frameHojeResto")
        self.labelHojeResto = QtWidgets.QLabel(self.frameHojeResto)
        self.labelHojeResto.setGeometry(QtCore.QRect(0, 0, 54, 17))
        self.labelHojeResto.setObjectName("labelHojeResto")
        self.labelHojeRestaV = QtWidgets.QLabel(self.frameHojeResto)
        self.labelHojeRestaV.setGeometry(QtCore.QRect(50, 0, 71, 17))
        self.labelHojeRestaV.setObjectName("labelHojeRestaV")
        self.progressBarHoje = QtWidgets.QProgressBar(self.boxHoje)
        self.progressBarHoje.setGeometry(QtCore.QRect(0, 100, 141, 31))
        self.progressBarHoje.setMaximum(100)
        self.progressBarHoje.setProperty("value", 24)
        self.progressBarHoje.setObjectName("progressBarHoje")
        self.boxMes = QtWidgets.QGroupBox(self.frame)
        self.boxMes.setGeometry(QtCore.QRect(350, 0, 141, 131))
        self.boxMes.setObjectName("boxMes")
        self.frameMesGasto = QtWidgets.QFrame(self.boxMes)
        self.frameMesGasto.setGeometry(QtCore.QRect(10, 30, 121, 21))
        self.frameMesGasto.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMesGasto.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMesGasto.setObjectName("frameMesGasto")
        self.labelMesGasto = QtWidgets.QLabel(self.frameMesGasto)
        self.labelMesGasto.setGeometry(QtCore.QRect(0, 0, 54, 17))
        self.labelMesGasto.setObjectName("labelMesGasto")
        self.labelMesGastoV = QtWidgets.QLabel(self.frameMesGasto)
        self.labelMesGastoV.setGeometry(QtCore.QRect(50, 0, 71, 17))
        self.labelMesGastoV.setObjectName("labelMesGastoV")
        self.frameMesLimite = QtWidgets.QFrame(self.boxMes)
        self.frameMesLimite.setGeometry(QtCore.QRect(10, 50, 121, 21))
        self.frameMesLimite.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMesLimite.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMesLimite.setObjectName("frameMesLimite")
        self.labelMesLimite = QtWidgets.QLabel(self.frameMesLimite)
        self.labelMesLimite.setGeometry(QtCore.QRect(0, 0, 54, 17))
        self.labelMesLimite.setObjectName("labelMesLimite")
        self.labelMesLimiteV = QtWidgets.QLabel(self.frameMesLimite)
        self.labelMesLimiteV.setGeometry(QtCore.QRect(50, 0, 71, 17))
        self.labelMesLimiteV.setObjectName("labelMesLimiteV")
        self.frameMesResta = QtWidgets.QFrame(self.boxMes)
        self.frameMesResta.setGeometry(QtCore.QRect(10, 70, 121, 21))
        self.frameMesResta.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMesResta.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMesResta.setObjectName("frameMesResta")
        self.labelMesResta = QtWidgets.QLabel(self.frameMesResta)
        self.labelMesResta.setGeometry(QtCore.QRect(0, 0, 54, 17))
        self.labelMesResta.setObjectName("labelMesResta")
        self.labelMesRestaV = QtWidgets.QLabel(self.frameMesResta)
        self.labelMesRestaV.setGeometry(QtCore.QRect(50, 0, 71, 17))
        self.labelMesRestaV.setObjectName("labelMesRestaV")
        self.progressBarMes = QtWidgets.QProgressBar(self.boxMes)
        self.progressBarMes.setGeometry(QtCore.QRect(0, 100, 141, 31))
        self.progressBarMes.setProperty("value", 24)
        self.progressBarMes.setObjectName("progressBarMes")
        self.boxSemana = QtWidgets.QGroupBox(self.frame)
        self.boxSemana.setGeometry(QtCore.QRect(190, 0, 141, 131))
        self.boxSemana.setStyleSheet("")
        self.boxSemana.setObjectName("boxSemana")
        self.frameSemanaGasto = QtWidgets.QFrame(self.boxSemana)
        self.frameSemanaGasto.setGeometry(QtCore.QRect(10, 30, 121, 21))
        self.frameSemanaGasto.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSemanaGasto.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSemanaGasto.setObjectName("frameSemanaGasto")
        self.labelSemanaGasto = QtWidgets.QLabel(self.frameSemanaGasto)
        self.labelSemanaGasto.setGeometry(QtCore.QRect(0, 0, 54, 17))
        self.labelSemanaGasto.setObjectName("labelSemanaGasto")
        self.labelSemanaGastoV = QtWidgets.QLabel(self.frameSemanaGasto)
        self.labelSemanaGastoV.setGeometry(QtCore.QRect(50, 0, 71, 17))
        self.labelSemanaGastoV.setObjectName("labelSemanaGastoV")
        self.frameSemanaLimite = QtWidgets.QFrame(self.boxSemana)
        self.frameSemanaLimite.setGeometry(QtCore.QRect(10, 50, 121, 21))
        self.frameSemanaLimite.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSemanaLimite.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSemanaLimite.setObjectName("frameSemanaLimite")
        self.labelSemanaLimite = QtWidgets.QLabel(self.frameSemanaLimite)
        self.labelSemanaLimite.setGeometry(QtCore.QRect(0, 0, 54, 17))
        self.labelSemanaLimite.setObjectName("labelSemanaLimite")
        self.labelSemanaLimiteV = QtWidgets.QLabel(self.frameSemanaLimite)
        self.labelSemanaLimiteV.setGeometry(QtCore.QRect(50, 0, 71, 17))
        self.labelSemanaLimiteV.setObjectName("labelSemanaLimiteV")
        self.frameSemanaResta = QtWidgets.QFrame(self.boxSemana)
        self.frameSemanaResta.setGeometry(QtCore.QRect(10, 70, 121, 21))
        self.frameSemanaResta.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSemanaResta.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSemanaResta.setObjectName("frameSemanaResta")
        self.labelSemanaResta = QtWidgets.QLabel(self.frameSemanaResta)
        self.labelSemanaResta.setGeometry(QtCore.QRect(0, 0, 54, 17))
        self.labelSemanaResta.setObjectName("labelSemanaResta")
        self.labelSemanaRestaV = QtWidgets.QLabel(self.frameSemanaResta)
        self.labelSemanaRestaV.setGeometry(QtCore.QRect(50, 0, 71, 17))
        self.labelSemanaRestaV.setObjectName("labelSemanaRestaV")
        self.progressBarSemana = QtWidgets.QProgressBar(self.boxSemana)
        self.progressBarSemana.setGeometry(QtCore.QRect(0, 100, 141, 31))
        self.progressBarSemana.setMaximum(100)
        self.progressBarSemana.setProperty("value", 24)
        self.progressBarSemana.setObjectName("progressBarSemana")
        self.groupDia = QtWidgets.QGroupBox(self.boxStatus)
        self.groupDia.setGeometry(QtCore.QRect(10, 20, 531, 55))
        self.groupDia.setObjectName("groupDia")
        self.frameTotalEntrada = QtWidgets.QFrame(self.groupDia)
        self.frameTotalEntrada.setGeometry(QtCore.QRect(10, 30, 151, 21))
        self.frameTotalEntrada.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTotalEntrada.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTotalEntrada.setObjectName("frameTotalEntrada")
        self.labelTotalEntrada = QtWidgets.QLabel(self.frameTotalEntrada)
        self.labelTotalEntrada.setGeometry(QtCore.QRect(20, 0, 54, 17))
        self.labelTotalEntrada.setObjectName("labelTotalEntrada")
        self.labelTotalEntradaV = QtWidgets.QLabel(self.frameTotalEntrada)
        self.labelTotalEntradaV.setGeometry(QtCore.QRect(80, 0, 71, 17))
        self.labelTotalEntradaV.setObjectName("labelTotalEntradaV")
        self.frameTotalFixo = QtWidgets.QFrame(self.groupDia)
        self.frameTotalFixo.setGeometry(QtCore.QRect(180, 30, 171, 21))
        self.frameTotalFixo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTotalFixo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTotalFixo.setObjectName("frameTotalFixo")
        self.labelTotalFixo = QtWidgets.QLabel(self.frameTotalFixo)
        self.labelTotalFixo.setGeometry(QtCore.QRect(20, 0, 81, 17))
        self.labelTotalFixo.setObjectName("labelTotalFixo")
        self.labelTotalFixoV = QtWidgets.QLabel(self.frameTotalFixo)
        self.labelTotalFixoV.setGeometry(QtCore.QRect(100, 0, 71, 17))
        self.labelTotalFixoV.setObjectName("labelTotalFixoV")
        self.frameTotalReserva = QtWidgets.QFrame(self.groupDia)
        self.frameTotalReserva.setGeometry(QtCore.QRect(370, 30, 151, 21))
        self.frameTotalReserva.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTotalReserva.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTotalReserva.setObjectName("frameTotalReserva")
        self.labelTotalReserva = QtWidgets.QLabel(self.frameTotalReserva)
        self.labelTotalReserva.setGeometry(QtCore.QRect(20, 0, 54, 17))
        self.labelTotalReserva.setObjectName("labelTotalReserva")
        self.labelTotalReservaV = QtWidgets.QLabel(self.frameTotalReserva)
        self.labelTotalReservaV.setGeometry(QtCore.QRect(80, 0, 71, 17))
        self.labelTotalReservaV.setObjectName("labelTotalReservaV")
        self.stackedWidget = QtWidgets.QStackedWidget(self.Hoje)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(130, 240, 511, 291))
        self.stackedWidget.setMouseTracking(False)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageGastos = QtWidgets.QWidget()
        self.pageGastos.setObjectName("pageGastos")
        self.boxGastos = QtWidgets.QGroupBox(self.pageGastos)
        self.boxGastos.setGeometry(QtCore.QRect(0, 0, 511, 291))
        self.boxGastos.setObjectName("boxGastos")
        self.treeSaida = QtWidgets.QTreeWidget(self.boxGastos)
        self.treeSaida.setGeometry(QtCore.QRect(0, 20, 511, 271))
        self.treeSaida.setAlternatingRowColors(True)
        self.treeSaida.setRootIsDecorated(True)
        self.treeSaida.setUniformRowHeights(False)
        self.treeSaida.setItemsExpandable(False)
        self.treeSaida.setWordWrap(True)
        self.treeSaida.setHeaderHidden(True)
        self.treeSaida.setObjectName("treeSaida")
        self.treeSaida.header().setVisible(False)
        self.treeSaida.header().setCascadingSectionResizes(False)
        self.treeSaida.header().setHighlightSections(False)
        self.stackedWidget.addWidget(self.pageGastos)
        self.pageEntrada = QtWidgets.QWidget()
        self.pageEntrada.setObjectName("pageEntrada")
        self.boxEntrada = QtWidgets.QGroupBox(self.pageEntrada)
        self.boxEntrada.setGeometry(QtCore.QRect(0, 0, 511, 291))
        self.boxEntrada.setObjectName("boxEntrada")
        self.treeEntrada = QtWidgets.QTreeWidget(self.boxEntrada)
        self.treeEntrada.setGeometry(QtCore.QRect(0, 20, 511, 271))
        self.treeEntrada.setAlternatingRowColors(True)
        self.treeEntrada.setWordWrap(True)
        self.treeEntrada.setObjectName("treeEntrada")
        self.treeEntrada.header().setVisible(False)
        self.stackedWidget.addWidget(self.pageEntrada)
        self.pageFixo = QtWidgets.QWidget()
        self.pageFixo.setObjectName("pageFixo")
        self.boxFixo = QtWidgets.QGroupBox(self.pageFixo)
        self.boxFixo.setGeometry(QtCore.QRect(0, 0, 511, 291))
        self.boxFixo.setObjectName("boxFixo")
        self.treeFixo = QtWidgets.QTreeWidget(self.boxFixo)
        self.treeFixo.setGeometry(QtCore.QRect(0, 20, 511, 271))
        self.treeFixo.setAlternatingRowColors(True)
        self.treeFixo.setRootIsDecorated(True)
        self.treeFixo.setUniformRowHeights(False)
        self.treeFixo.setItemsExpandable(False)
        self.treeFixo.setWordWrap(True)
        self.treeFixo.setHeaderHidden(True)
        self.treeFixo.setObjectName("treeFixo")
        self.treeFixo.header().setVisible(False)
        self.treeFixo.header().setCascadingSectionResizes(False)
        self.treeFixo.header().setHighlightSections(False)
        self.stackedWidget.addWidget(self.pageFixo)
        self.pageReserva = QtWidgets.QWidget()
        self.pageReserva.setObjectName("pageReserva")
        self.boxSaidas_2 = QtWidgets.QGroupBox(self.pageReserva)
        self.boxSaidas_2.setGeometry(QtCore.QRect(0, 0, 521, 291))
        self.boxSaidas_2.setObjectName("boxSaidas_2")
        self.treeReserva = QtWidgets.QTreeWidget(self.boxSaidas_2)
        self.treeReserva.setGeometry(QtCore.QRect(0, 20, 511, 271))
        self.treeReserva.setAlternatingRowColors(True)
        self.treeReserva.setRootIsDecorated(True)
        self.treeReserva.setUniformRowHeights(False)
        self.treeReserva.setItemsExpandable(False)
        self.treeReserva.setWordWrap(True)
        self.treeReserva.setHeaderHidden(True)
        self.treeReserva.setObjectName("treeReserva")
        self.treeReserva.header().setVisible(False)
        self.treeReserva.header().setCascadingSectionResizes(False)
        self.treeReserva.header().setHighlightSections(False)
        self.stackedWidget.addWidget(self.pageReserva)
        self.listMenu = QtWidgets.QListWidget(self.Hoje)
        self.listMenu.setGeometry(QtCore.QRect(60, 260, 71, 192))
        self.listMenu.setAlternatingRowColors(False)
        self.listMenu.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.listMenu.setProperty("isWrapping", True)
        self.listMenu.setObjectName("listMenu")
        item = QtWidgets.QListWidgetItem()
        self.listMenu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listMenu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listMenu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listMenu.addItem(item)
        self.graficoPizza = PlotPizza(self.Hoje)
        self.graficoPizza.setGeometry(QtCore.QRect(670, 10, 551, 261))
        self.graficoPizza.setObjectName("graficoPizza")
        self.graficoBarra = PlotBarra(self.Hoje)
        self.graficoBarra.setGeometry(QtCore.QRect(670, 270, 551, 261))
        self.graficoBarra.setObjectName("graficoBarra")
        self.botaoExcluir = QtWidgets.QPushButton(self.Hoje)
        self.botaoExcluir.setGeometry(QtCore.QRect(40, 490, 80, 25))
        self.botaoExcluir.setObjectName("botaoExcluir")
        self.toolAdicionar = QtWidgets.QToolButton(self.Hoje)
        self.toolAdicionar.setGeometry(QtCore.QRect(20, 20, 91, 41))
        self.toolAdicionar.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.toolAdicionar.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolAdicionar.setAutoRaise(True)
        self.toolAdicionar.setArrowType(QtCore.Qt.DownArrow)
        self.toolAdicionar.setObjectName("toolAdicionar")
        self.boxAjuste = QtWidgets.QGroupBox(self.Hoje)
        self.boxAjuste.setGeometry(QtCore.QRect(10, 180, 121, 71))
        self.boxAjuste.setAlignment(QtCore.Qt.AlignCenter)
        self.boxAjuste.setObjectName("boxAjuste")
        self.labelAjuste = QtWidgets.QLabel(self.boxAjuste)
        self.labelAjuste.setGeometry(QtCore.QRect(0, 20, 121, 51))
        self.labelAjuste.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelAjuste.setObjectName("labelAjuste")
        self.boxLimiteDia = QtWidgets.QGroupBox(self.Hoje)
        self.boxLimiteDia.setGeometry(QtCore.QRect(10, 130, 121, 41))
        self.boxLimiteDia.setAlignment(QtCore.Qt.AlignCenter)
        self.boxLimiteDia.setObjectName("boxLimiteDia")
        self.labelLimiteDia = QtWidgets.QLabel(self.boxLimiteDia)
        self.labelLimiteDia.setGeometry(QtCore.QRect(0, 20, 121, 20))
        self.labelLimiteDia.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLimiteDia.setObjectName("labelLimiteDia")
        self.boxMedia = QtWidgets.QGroupBox(self.Hoje)
        self.boxMedia.setGeometry(QtCore.QRect(10, 80, 121, 41))
        self.boxMedia.setAlignment(QtCore.Qt.AlignCenter)
        self.boxMedia.setObjectName("boxMedia")
        self.labelMedia = QtWidgets.QLabel(self.boxMedia)
        self.labelMedia.setGeometry(QtCore.QRect(0, 20, 121, 20))
        self.labelMedia.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMedia.setObjectName("labelMedia")
        self.botaoAjuste = QtWidgets.QPushButton(self.Hoje)
        self.botaoAjuste.setGeometry(QtCore.QRect(1180, 0, 51, 23))
        self.botaoAjuste.setObjectName("botaoAjuste")
        self.tabWidget.addTab(self.Hoje, "")
        self.Geral = QtWidgets.QWidget()
        self.Geral.setObjectName("Geral")
        self.boxGeralGastos = QtWidgets.QGroupBox(self.Geral)
        self.boxGeralGastos.setGeometry(QtCore.QRect(10, 20, 511, 251))
        self.boxGeralGastos.setObjectName("boxGeralGastos")
        self.treeGeralGastos = QtWidgets.QTreeWidget(self.boxGeralGastos)
        self.treeGeralGastos.setGeometry(QtCore.QRect(0, 50, 511, 201))
        self.treeGeralGastos.setAlternatingRowColors(True)
        self.treeGeralGastos.setRootIsDecorated(True)
        self.treeGeralGastos.setUniformRowHeights(False)
        self.treeGeralGastos.setItemsExpandable(False)
        self.treeGeralGastos.setWordWrap(True)
        self.treeGeralGastos.setHeaderHidden(True)
        self.treeGeralGastos.setObjectName("treeGeralGastos")
        self.treeGeralGastos.header().setVisible(False)
        self.treeGeralGastos.header().setCascadingSectionResizes(False)
        self.treeGeralGastos.header().setHighlightSections(False)
        self.buttonNovoRecorrente = QtWidgets.QPushButton(self.boxGeralGastos)
        self.buttonNovoRecorrente.setGeometry(QtCore.QRect(420, 20, 75, 23))
        self.buttonNovoRecorrente.setObjectName("buttonNovoRecorrente")
        self.boxFiltro = QtWidgets.QGroupBox(self.Geral)
        self.boxFiltro.setGeometry(QtCore.QRect(540, 10, 681, 291))
        self.boxFiltro.setObjectName("boxFiltro")
        self.comboSub = QtWidgets.QComboBox(self.boxFiltro)
        self.comboSub.setGeometry(QtCore.QRect(360, 50, 111, 25))
        self.comboSub.setObjectName("comboSub")
        self.inputFiltro = QtWidgets.QLineEdit(self.boxFiltro)
        self.inputFiltro.setGeometry(QtCore.QRect(110, 50, 111, 25))
        self.inputFiltro.setObjectName("inputFiltro")
        self.comboCategoria = QtWidgets.QComboBox(self.boxFiltro)
        self.comboCategoria.setGeometry(QtCore.QRect(230, 50, 121, 25))
        self.comboCategoria.setObjectName("comboCategoria")
        self.dateInicio = QtWidgets.QDateEdit(self.boxFiltro)
        self.dateInicio.setGeometry(QtCore.QRect(480, 50, 91, 26))
        self.dateInicio.setObjectName("dateInicio")
        self.dateFim = QtWidgets.QDateEdit(self.boxFiltro)
        self.dateFim.setGeometry(QtCore.QRect(580, 50, 91, 26))
        self.dateFim.setObjectName("dateFim")
        self.treeSaida_2 = QtWidgets.QTreeWidget(self.boxFiltro)
        self.treeSaida_2.setGeometry(QtCore.QRect(10, 90, 661, 181))
        self.treeSaida_2.setAlternatingRowColors(True)
        self.treeSaida_2.setRootIsDecorated(True)
        self.treeSaida_2.setUniformRowHeights(False)
        self.treeSaida_2.setItemsExpandable(False)
        self.treeSaida_2.setWordWrap(True)
        self.treeSaida_2.setHeaderHidden(True)
        self.treeSaida_2.setObjectName("treeSaida_2")
        self.treeSaida_2.header().setVisible(False)
        self.treeSaida_2.header().setCascadingSectionResizes(False)
        self.treeSaida_2.header().setHighlightSections(False)
        self.label = QtWidgets.QLabel(self.boxFiltro)
        self.label.setGeometry(QtCore.QRect(570, 270, 41, 17))
        self.label.setObjectName("label")
        self.checkRelCat = QtWidgets.QCheckBox(self.boxFiltro)
        self.checkRelCat.setGeometry(QtCore.QRect(230, 30, 121, 17))
        self.checkRelCat.setObjectName("checkRelCat")
        self.checkRelSub = QtWidgets.QCheckBox(self.boxFiltro)
        self.checkRelSub.setGeometry(QtCore.QRect(360, 30, 111, 17))
        self.checkRelSub.setObjectName("checkRelSub")
        self.checkRelInicio = QtWidgets.QCheckBox(self.boxFiltro)
        self.checkRelInicio.setGeometry(QtCore.QRect(480, 30, 61, 17))
        self.checkRelInicio.setObjectName("checkRelInicio")
        self.checkRelFim = QtWidgets.QCheckBox(self.boxFiltro)
        self.checkRelFim.setGeometry(QtCore.QRect(580, 30, 61, 17))
        self.checkRelFim.setObjectName("checkRelFim")
        self.checkRelNome = QtWidgets.QCheckBox(self.boxFiltro)
        self.checkRelNome.setGeometry(QtCore.QRect(110, 30, 61, 17))
        self.checkRelNome.setObjectName("checkRelNome")
        self.checkRelTipo = QtWidgets.QCheckBox(self.boxFiltro)
        self.checkRelTipo.setGeometry(QtCore.QRect(10, 30, 61, 17))
        self.checkRelTipo.setObjectName("checkRelTipo")
        self.comboTimpo = QtWidgets.QComboBox(self.boxFiltro)
        self.comboTimpo.setGeometry(QtCore.QRect(10, 50, 91, 25))
        self.comboTimpo.setObjectName("comboTimpo")
        self.comboTimpo.addItem("")
        self.comboTimpo.addItem("")
        self.comboTimpo.addItem("")
        self.comboTimpo.addItem("")
        self.labelSomaFiltro = QtWidgets.QLabel(self.boxFiltro)
        self.labelSomaFiltro.setGeometry(QtCore.QRect(610, 270, 61, 17))
        self.labelSomaFiltro.setObjectName("labelSomaFiltro")
        self.boxInvestimentos = QtWidgets.QGroupBox(self.Geral)
        self.boxInvestimentos.setGeometry(QtCore.QRect(10, 290, 511, 251))
        self.boxInvestimentos.setObjectName("boxInvestimentos")
        self.treeInvestimentos = QtWidgets.QTreeWidget(self.boxInvestimentos)
        self.treeInvestimentos.setGeometry(QtCore.QRect(0, 50, 511, 201))
        self.treeInvestimentos.setAlternatingRowColors(True)
        self.treeInvestimentos.setRootIsDecorated(True)
        self.treeInvestimentos.setUniformRowHeights(False)
        self.treeInvestimentos.setItemsExpandable(False)
        self.treeInvestimentos.setWordWrap(True)
        self.treeInvestimentos.setHeaderHidden(True)
        self.treeInvestimentos.setObjectName("treeInvestimentos")
        self.treeInvestimentos.header().setVisible(False)
        self.treeInvestimentos.header().setCascadingSectionResizes(False)
        self.treeInvestimentos.header().setHighlightSections(False)
        self.buttonNovoInvestimento = QtWidgets.QPushButton(self.boxInvestimentos)
        self.buttonNovoInvestimento.setGeometry(QtCore.QRect(420, 20, 75, 23))
        self.buttonNovoInvestimento.setObjectName("buttonNovoInvestimento")
        self.treeAno = QtWidgets.QTreeWidget(self.Geral)
        self.treeAno.setGeometry(QtCore.QRect(540, 320, 211, 221))
        self.treeAno.setObjectName("treeAno")
        self.treeAno.header().setVisible(False)
        self.graficoLinha = PlotLinha(self.Geral)
        self.graficoLinha.setGeometry(QtCore.QRect(760, 300, 461, 241))
        self.graficoLinha.setObjectName("graficoLinha")
        self.tabWidget.addTab(self.Geral, "")
        self.Dividas = QtWidgets.QWidget()
        self.Dividas.setObjectName("Dividas")
        self.pushButton_2 = QtWidgets.QPushButton(self.Dividas)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 20, 80, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.boxSaidas_3 = QtWidgets.QGroupBox(self.Dividas)
        self.boxSaidas_3.setGeometry(QtCore.QRect(10, 80, 441, 461))
        self.boxSaidas_3.setObjectName("boxSaidas_3")
        self.treeReserva_2 = QtWidgets.QTreeWidget(self.boxSaidas_3)
        self.treeReserva_2.setGeometry(QtCore.QRect(0, 20, 441, 441))
        self.treeReserva_2.setAlternatingRowColors(True)
        self.treeReserva_2.setRootIsDecorated(True)
        self.treeReserva_2.setUniformRowHeights(False)
        self.treeReserva_2.setItemsExpandable(False)
        self.treeReserva_2.setWordWrap(True)
        self.treeReserva_2.setHeaderHidden(True)
        self.treeReserva_2.setObjectName("treeReserva_2")
        self.treeReserva_2.header().setVisible(False)
        self.treeReserva_2.header().setCascadingSectionResizes(False)
        self.treeReserva_2.header().setHighlightSections(False)
        self.boxSaidas_4 = QtWidgets.QGroupBox(self.Dividas)
        self.boxSaidas_4.setGeometry(QtCore.QRect(460, 80, 441, 461))
        self.boxSaidas_4.setObjectName("boxSaidas_4")
        self.treeReserva_3 = QtWidgets.QTreeWidget(self.boxSaidas_4)
        self.treeReserva_3.setGeometry(QtCore.QRect(0, 20, 441, 441))
        self.treeReserva_3.setAlternatingRowColors(True)
        self.treeReserva_3.setRootIsDecorated(True)
        self.treeReserva_3.setUniformRowHeights(False)
        self.treeReserva_3.setItemsExpandable(False)
        self.treeReserva_3.setWordWrap(True)
        self.treeReserva_3.setHeaderHidden(True)
        self.treeReserva_3.setObjectName("treeReserva_3")
        self.treeReserva_3.header().setVisible(False)
        self.treeReserva_3.header().setCascadingSectionResizes(False)
        self.treeReserva_3.header().setHighlightSections(False)
        self.groupBox = QtWidgets.QGroupBox(self.Dividas)
        self.groupBox.setGeometry(QtCore.QRect(110, 0, 461, 71))
        self.groupBox.setObjectName("groupBox")
        self.boxMedia_2 = QtWidgets.QGroupBox(self.groupBox)
        self.boxMedia_2.setGeometry(QtCore.QRect(10, 20, 141, 41))
        self.boxMedia_2.setAlignment(QtCore.Qt.AlignCenter)
        self.boxMedia_2.setObjectName("boxMedia_2")
        self.labelMedia_2 = QtWidgets.QLabel(self.boxMedia_2)
        self.labelMedia_2.setGeometry(QtCore.QRect(0, 20, 141, 20))
        self.labelMedia_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMedia_2.setObjectName("labelMedia_2")
        self.boxLimiteDia_2 = QtWidgets.QGroupBox(self.groupBox)
        self.boxLimiteDia_2.setGeometry(QtCore.QRect(160, 20, 141, 41))
        self.boxLimiteDia_2.setAlignment(QtCore.Qt.AlignCenter)
        self.boxLimiteDia_2.setObjectName("boxLimiteDia_2")
        self.labelLimiteDia_2 = QtWidgets.QLabel(self.boxLimiteDia_2)
        self.labelLimiteDia_2.setGeometry(QtCore.QRect(0, 20, 141, 20))
        self.labelLimiteDia_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLimiteDia_2.setObjectName("labelLimiteDia_2")
        self.boxAjuste_2 = QtWidgets.QGroupBox(self.groupBox)
        self.boxAjuste_2.setGeometry(QtCore.QRect(310, 20, 141, 41))
        self.boxAjuste_2.setAlignment(QtCore.Qt.AlignCenter)
        self.boxAjuste_2.setObjectName("boxAjuste_2")
        self.labelAjuste_2 = QtWidgets.QLabel(self.boxAjuste_2)
        self.labelAjuste_2.setGeometry(QtCore.QRect(0, 20, 141, 20))
        self.labelAjuste_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAjuste_2.setObjectName("labelAjuste_2")
        self.boxSaidas_5 = QtWidgets.QGroupBox(self.Dividas)
        self.boxSaidas_5.setGeometry(QtCore.QRect(910, 80, 311, 461))
        self.boxSaidas_5.setObjectName("boxSaidas_5")
        self.treeReserva_4 = QtWidgets.QTreeWidget(self.boxSaidas_5)
        self.treeReserva_4.setGeometry(QtCore.QRect(0, 20, 311, 441))
        self.treeReserva_4.setAlternatingRowColors(True)
        self.treeReserva_4.setRootIsDecorated(True)
        self.treeReserva_4.setUniformRowHeights(False)
        self.treeReserva_4.setItemsExpandable(False)
        self.treeReserva_4.setWordWrap(True)
        self.treeReserva_4.setHeaderHidden(True)
        self.treeReserva_4.setObjectName("treeReserva_4")
        self.treeReserva_4.header().setVisible(False)
        self.treeReserva_4.header().setCascadingSectionResizes(False)
        self.treeReserva_4.header().setHighlightSections(False)
        self.tabWidget.addTab(self.Dividas, "")
        self.Config = QtWidgets.QWidget()
        self.Config.setObjectName("Config")
        self.boxCategorias = QtWidgets.QGroupBox(self.Config)
        self.boxCategorias.setGeometry(QtCore.QRect(100, 10, 381, 461))
        self.boxCategorias.setObjectName("boxCategorias")
        self.treeCategorias = QtWidgets.QTreeWidget(self.boxCategorias)
        self.treeCategorias.setGeometry(QtCore.QRect(0, 20, 381, 441))
        self.treeCategorias.setAlternatingRowColors(True)
        self.treeCategorias.setObjectName("treeCategorias")
        self.treeCategorias.header().setVisible(False)
        self.boxPessoas = QtWidgets.QGroupBox(self.Config)
        self.boxPessoas.setGeometry(QtCore.QRect(760, 10, 380, 461))
        self.boxPessoas.setObjectName("boxPessoas")
        self.treePessoas = QtWidgets.QTreeWidget(self.boxPessoas)
        self.treePessoas.setGeometry(QtCore.QRect(0, 20, 380, 441))
        self.treePessoas.setAlternatingRowColors(True)
        self.treePessoas.setObjectName("treePessoas")
        self.treePessoas.header().setVisible(False)
        self.treePessoas.header().setDefaultSectionSize(100)
        self.botaoCategoriaAdicionar = QtWidgets.QPushButton(self.Config)
        self.botaoCategoriaAdicionar.setGeometry(QtCore.QRect(150, 480, 131, 25))
        self.botaoCategoriaAdicionar.setObjectName("botaoCategoriaAdicionar")
        self.botaoPessoaAdicionar = QtWidgets.QPushButton(self.Config)
        self.botaoPessoaAdicionar.setGeometry(QtCore.QRect(810, 490, 111, 25))
        self.botaoPessoaAdicionar.setObjectName("botaoPessoaAdicionar")
        self.botaoCategoriaEditar = QtWidgets.QPushButton(self.Config)
        self.botaoCategoriaEditar.setGeometry(QtCore.QRect(340, 490, 80, 31))
        self.botaoCategoriaEditar.setObjectName("botaoCategoriaEditar")
        self.botaoPessoaEditar = QtWidgets.QPushButton(self.Config)
        self.botaoPessoaEditar.setGeometry(QtCore.QRect(1000, 490, 80, 25))
        self.botaoPessoaEditar.setObjectName("botaoPessoaEditar")
        self.botaoSubAdicionar = QtWidgets.QPushButton(self.Config)
        self.botaoSubAdicionar.setGeometry(QtCore.QRect(140, 510, 151, 25))
        self.botaoSubAdicionar.setObjectName("botaoSubAdicionar")
        self.tabWidget.addTab(self.Config, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Controle de Gastos"))
        self.boxHoje.setAccessibleName(_translate("Form", "progresso"))
        self.boxHoje.setTitle(_translate("Form", "Diário"))
        self.labelHojeGasto.setText(_translate("Form", "Gasto:"))
        self.labelHojeGastoV.setText(_translate("Form", "R$1000,00"))
        self.labelHojeLimite.setText(_translate("Form", "Limite:"))
        self.labelHojeLimiteV.setText(_translate("Form", "R$1000,00"))
        self.labelHojeResto.setText(_translate("Form", "Resta:"))
        self.labelHojeRestaV.setText(_translate("Form", "R$1000,00"))
        self.boxMes.setAccessibleName(_translate("Form", "progresso"))
        self.boxMes.setTitle(_translate("Form", "Mensal"))
        self.labelMesGasto.setText(_translate("Form", "Gasto:"))
        self.labelMesGastoV.setText(_translate("Form", "R$1000,00"))
        self.labelMesLimite.setText(_translate("Form", "Limite:"))
        self.labelMesLimiteV.setText(_translate("Form", "R$1000,00"))
        self.labelMesResta.setText(_translate("Form", "Resta:"))
        self.labelMesRestaV.setText(_translate("Form", "R$1000,00"))
        self.boxSemana.setAccessibleName(_translate("Form", "progresso"))
        self.boxSemana.setTitle(_translate("Form", "Semanal"))
        self.labelSemanaGasto.setText(_translate("Form", "Gasto:"))
        self.labelSemanaGastoV.setText(_translate("Form", "R$1000,00"))
        self.labelSemanaLimite.setText(_translate("Form", "Limite:"))
        self.labelSemanaLimiteV.setText(_translate("Form", "R$1000,00"))
        self.labelSemanaResta.setText(_translate("Form", "Resta:"))
        self.labelSemanaRestaV.setText(_translate("Form", "R$1000,00"))
        self.groupDia.setTitle(_translate("Form", "Dia: 02 de 28 (07%)"))
        self.labelTotalEntrada.setText(_translate("Form", "Entrada:"))
        self.labelTotalEntradaV.setText(_translate("Form", "R$1000,00"))
        self.labelTotalFixo.setText(_translate("Form", "Gastos Fixos:"))
        self.labelTotalFixoV.setText(_translate("Form", "R$1000,00"))
        self.labelTotalReserva.setText(_translate("Form", "Reserva:"))
        self.labelTotalReservaV.setText(_translate("Form", "R$1000,00"))
        self.boxGastos.setTitle(_translate("Form", "Gastos"))
        self.treeSaida.setSortingEnabled(True)
        self.treeSaida.headerItem().setText(0, _translate("Form", "Data"))
        self.treeSaida.headerItem().setText(1, _translate("Form", "Item"))
        self.treeSaida.headerItem().setText(2, _translate("Form", "Categoria"))
        self.treeSaida.headerItem().setText(3, _translate("Form", "Sub-categoria"))
        self.treeSaida.headerItem().setText(4, _translate("Form", "Valor"))
        self.boxEntrada.setTitle(_translate("Form", "Entrada"))
        self.treeEntrada.setSortingEnabled(True)
        self.treeEntrada.headerItem().setText(0, _translate("Form", "Item"))
        self.treeEntrada.headerItem().setText(1, _translate("Form", "Previsão"))
        self.treeEntrada.headerItem().setText(2, _translate("Form", "Data"))
        self.treeEntrada.headerItem().setText(3, _translate("Form", "Valor"))
        self.boxFixo.setTitle(_translate("Form", "Saídas do Mês"))
        self.treeFixo.setSortingEnabled(True)
        self.treeFixo.headerItem().setText(0, _translate("Form", "Item"))
        self.treeFixo.headerItem().setText(1, _translate("Form", "Vencimento"))
        self.treeFixo.headerItem().setText(2, _translate("Form", "Pago"))
        self.treeFixo.headerItem().setText(3, _translate("Form", "Categoria"))
        self.treeFixo.headerItem().setText(4, _translate("Form", "Sub-categoria"))
        self.treeFixo.headerItem().setText(5, _translate("Form", "Valor"))
        self.boxSaidas_2.setTitle(_translate("Form", "Reserva"))
        self.treeReserva.setSortingEnabled(True)
        self.treeReserva.headerItem().setText(0, _translate("Form", "Item"))
        self.treeReserva.headerItem().setText(1, _translate("Form", "Valor"))
        self.treeReserva.headerItem().setText(2, _translate("Form", "Comentário"))
        self.listMenu.setAccessibleName(_translate("Form", "selecao"))
        __sortingEnabled = self.listMenu.isSortingEnabled()
        self.listMenu.setSortingEnabled(False)
        item = self.listMenu.item(0)
        item.setText(_translate("Form", "Gastos"))
        item = self.listMenu.item(1)
        item.setText(_translate("Form", "Entrada"))
        item = self.listMenu.item(2)
        item.setText(_translate("Form", "Fixo"))
        item = self.listMenu.item(3)
        item.setText(_translate("Form", "Reserva"))
        self.listMenu.setSortingEnabled(__sortingEnabled)
        self.botaoExcluir.setText(_translate("Form", "Excluir"))
        self.toolAdicionar.setAccessibleName(_translate("Form", "tool"))
        self.toolAdicionar.setText(_translate("Form", "Adicionar"))
        self.boxAjuste.setAccessibleName(_translate("Form", "quadro"))
        self.boxAjuste.setTitle(_translate("Form", "{ajuste}"))
        self.labelAjuste.setText(_translate("Form", "R$100,00"))
        self.boxLimiteDia.setAccessibleName(_translate("Form", "quadro"))
        self.boxLimiteDia.setTitle(_translate("Form", "Limite por dia"))
        self.labelLimiteDia.setText(_translate("Form", "R$100,00"))
        self.boxMedia.setAccessibleName(_translate("Form", "quadro"))
        self.boxMedia.setTitle(_translate("Form", "Média por dia"))
        self.labelMedia.setText(_translate("Form", "R$100,00"))
        self.botaoAjuste.setText(_translate("Form", "Ajuste"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Hoje), _translate("Form", "Hoje"))
        self.boxGeralGastos.setTitle(_translate("Form", "Gastos recorrentes"))
        self.treeGeralGastos.setSortingEnabled(True)
        self.treeGeralGastos.headerItem().setText(0, _translate("Form", "Item"))
        self.treeGeralGastos.headerItem().setText(1, _translate("Form", "Tipo"))
        self.treeGeralGastos.headerItem().setText(2, _translate("Form", "Categoria"))
        self.treeGeralGastos.headerItem().setText(3, _translate("Form", "Sub-categoria"))
        self.treeGeralGastos.headerItem().setText(4, _translate("Form", "Valor"))
        self.buttonNovoRecorrente.setText(_translate("Form", "Novo"))
        self.boxFiltro.setTitle(_translate("Form", "Filtro"))
        self.treeSaida_2.setSortingEnabled(True)
        self.treeSaida_2.headerItem().setText(0, _translate("Form", "Item"))
        self.treeSaida_2.headerItem().setText(1, _translate("Form", "Data"))
        self.treeSaida_2.headerItem().setText(2, _translate("Form", "Categoria"))
        self.treeSaida_2.headerItem().setText(3, _translate("Form", "Sub-categoria"))
        self.treeSaida_2.headerItem().setText(4, _translate("Form", "Valor"))
        self.treeSaida_2.headerItem().setText(5, _translate("Form", "Comentários"))
        self.label.setText(_translate("Form", "Soma: "))
        self.checkRelCat.setText(_translate("Form", "Categoria"))
        self.checkRelSub.setText(_translate("Form", "Sub-categoria"))
        self.checkRelInicio.setText(_translate("Form", "Início"))
        self.checkRelFim.setText(_translate("Form", "Fim"))
        self.checkRelNome.setText(_translate("Form", "Nome"))
        self.checkRelTipo.setText(_translate("Form", "Tipo"))
        self.comboTimpo.setItemText(0, _translate("Form", "Gasto"))
        self.comboTimpo.setItemText(1, _translate("Form", "Entrada"))
        self.comboTimpo.setItemText(2, _translate("Form", "Fixo"))
        self.comboTimpo.setItemText(3, _translate("Form", "Reserva"))
        self.labelSomaFiltro.setText(_translate("Form", "R$0,00"))
        self.boxInvestimentos.setTitle(_translate("Form", "Investimentos"))
        self.treeInvestimentos.setSortingEnabled(True)
        self.treeInvestimentos.headerItem().setText(0, _translate("Form", "Item"))
        self.treeInvestimentos.headerItem().setText(1, _translate("Form", "Tipo"))
        self.treeInvestimentos.headerItem().setText(2, _translate("Form", "Categoria"))
        self.treeInvestimentos.headerItem().setText(3, _translate("Form", "Sub-categoria"))
        self.treeInvestimentos.headerItem().setText(4, _translate("Form", "Valor"))
        self.buttonNovoInvestimento.setText(_translate("Form", "Novo"))
        self.treeAno.headerItem().setText(0, _translate("Form", "Mês"))
        self.treeAno.headerItem().setText(1, _translate("Form", "Entrada"))
        self.treeAno.headerItem().setText(2, _translate("Form", "Saída"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Geral), _translate("Form", "Geral"))
        self.pushButton_2.setText(_translate("Form", "Nova Dívida"))
        self.boxSaidas_3.setTitle(_translate("Form", "Eu devo..."))
        self.treeReserva_2.setSortingEnabled(True)
        self.treeReserva_2.headerItem().setText(0, _translate("Form", "Item"))
        self.treeReserva_2.headerItem().setText(1, _translate("Form", "Valor"))
        self.treeReserva_2.headerItem().setText(2, _translate("Form", "Pessoa"))
        self.treeReserva_2.headerItem().setText(3, _translate("Form", "Comentário"))
        self.boxSaidas_4.setTitle(_translate("Form", "Me deve..."))
        self.treeReserva_3.setSortingEnabled(True)
        self.treeReserva_3.headerItem().setText(0, _translate("Form", "Item"))
        self.treeReserva_3.headerItem().setText(1, _translate("Form", "Valor"))
        self.treeReserva_3.headerItem().setText(2, _translate("Form", "Comentário"))
        self.treeReserva_3.headerItem().setText(3, _translate("Form", "Pessoa"))
        self.groupBox.setTitle(_translate("Form", "Soma"))
        self.boxMedia_2.setAccessibleName(_translate("Form", "quadro"))
        self.boxMedia_2.setTitle(_translate("Form", "Eu devo..."))
        self.labelMedia_2.setText(_translate("Form", "R$100,00"))
        self.boxLimiteDia_2.setAccessibleName(_translate("Form", "quadro"))
        self.boxLimiteDia_2.setTitle(_translate("Form", "Me devem..."))
        self.labelLimiteDia_2.setText(_translate("Form", "R$100,00"))
        self.boxAjuste_2.setAccessibleName(_translate("Form", "quadro"))
        self.boxAjuste_2.setTitle(_translate("Form", "Geral"))
        self.labelAjuste_2.setText(_translate("Form", "R$100,00"))
        self.boxSaidas_5.setTitle(_translate("Form", "Pessoas"))
        self.treeReserva_4.setSortingEnabled(True)
        self.treeReserva_4.headerItem().setText(0, _translate("Form", "Pessoa"))
        self.treeReserva_4.headerItem().setText(1, _translate("Form", "Valor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Dividas), _translate("Form", "Dívidas"))
        self.boxCategorias.setTitle(_translate("Form", "Categorias"))
        self.treeCategorias.headerItem().setText(0, _translate("Form", "nome"))
        self.treeCategorias.headerItem().setText(1, _translate("Form", "status"))
        self.boxPessoas.setTitle(_translate("Form", "Pessoas"))
        self.treePessoas.headerItem().setText(0, _translate("Form", "nome"))
        self.treePessoas.headerItem().setText(1, _translate("Form", "status"))
        self.botaoCategoriaAdicionar.setText(_translate("Form", "Adicionar Categoria"))
        self.botaoPessoaAdicionar.setText(_translate("Form", "Adicionar Pessoa"))
        self.botaoCategoriaEditar.setText(_translate("Form", "Editar"))
        self.botaoPessoaEditar.setText(_translate("Form", "Editar"))
        self.botaoSubAdicionar.setText(_translate("Form", "Adicionar Sub-Categoria"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Config), _translate("Form", "Configurações"))

from ui.plotcanvas import PlotBarra, PlotLinha, PlotPizza

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

