# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recorrentes.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(464, 300)
        Form.setMinimumSize(QtCore.QSize(300, 300))
        Form.setMaximumSize(QtCore.QSize(9999, 9999))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelGasto = QtWidgets.QLabel(Form)
        self.labelGasto.setObjectName("labelGasto")
        self.horizontalLayout_2.addWidget(self.labelGasto)
        self.inputGasto = QtWidgets.QLineEdit(Form)
        self.inputGasto.setObjectName("inputGasto")
        self.horizontalLayout_2.addWidget(self.inputGasto)
        self.labelCategoria_2 = QtWidgets.QLabel(Form)
        self.labelCategoria_2.setObjectName("labelCategoria_2")
        self.horizontalLayout_2.addWidget(self.labelCategoria_2)
        self.comboCategoria_2 = QtWidgets.QComboBox(Form)
        self.comboCategoria_2.setObjectName("comboCategoria_2")
        self.comboCategoria_2.addItem("")
        self.comboCategoria_2.addItem("")
        self.comboCategoria_2.addItem("")
        self.horizontalLayout_2.addWidget(self.comboCategoria_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelCategoria = QtWidgets.QLabel(Form)
        self.labelCategoria.setObjectName("labelCategoria")
        self.horizontalLayout_3.addWidget(self.labelCategoria)
        self.comboCategoria = QtWidgets.QComboBox(Form)
        self.comboCategoria.setObjectName("comboCategoria")
        self.horizontalLayout_3.addWidget(self.comboCategoria)
        self.labelSub = QtWidgets.QLabel(Form)
        self.labelSub.setObjectName("labelSub")
        self.horizontalLayout_3.addWidget(self.labelSub)
        self.comboSub = QtWidgets.QComboBox(Form)
        self.comboSub.setObjectName("comboSub")
        self.horizontalLayout_3.addWidget(self.comboSub)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelValor = QtWidgets.QLabel(Form)
        self.labelValor.setObjectName("labelValor")
        self.horizontalLayout_4.addWidget(self.labelValor)
        self.labelValor_2 = QtWidgets.QLabel(Form)
        self.labelValor_2.setObjectName("labelValor_2")
        self.horizontalLayout_4.addWidget(self.labelValor_2)
        self.spinValor = QtWidgets.QDoubleSpinBox(Form)
        self.spinValor.setDecimals(2)
        self.spinValor.setMaximum(99999.99)
        self.spinValor.setProperty("value", 0.0)
        self.spinValor.setObjectName("spinValor")
        self.horizontalLayout_4.addWidget(self.spinValor)
        self.labelValor_3 = QtWidgets.QLabel(Form)
        self.labelValor_3.setObjectName("labelValor_3")
        self.horizontalLayout_4.addWidget(self.labelValor_3)
        self.spinValor_2 = QtWidgets.QSpinBox(Form)
        self.spinValor_2.setObjectName("spinValor_2")
        self.horizontalLayout_4.addWidget(self.spinValor_2)
        self.labelPrevisao = QtWidgets.QLabel(Form)
        self.labelPrevisao.setObjectName("labelPrevisao")
        self.horizontalLayout_4.addWidget(self.labelPrevisao)
        self.spinValor_3 = QtWidgets.QSpinBox(Form)
        self.spinValor_3.setObjectName("spinValor_3")
        self.horizontalLayout_4.addWidget(self.spinValor_3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.labelComentario = QtWidgets.QLabel(Form)
        self.labelComentario.setObjectName("labelComentario")
        self.verticalLayout.addWidget(self.labelComentario)
        self.textComentario = QtWidgets.QTextEdit(Form)
        self.textComentario.setObjectName("textComentario")
        self.verticalLayout.addWidget(self.textComentario)
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.inputGasto, self.comboCategoria_2)
        Form.setTabOrder(self.comboCategoria_2, self.comboCategoria)
        Form.setTabOrder(self.comboCategoria, self.comboSub)
        Form.setTabOrder(self.comboSub, self.spinValor)
        Form.setTabOrder(self.spinValor, self.spinValor_2)
        Form.setTabOrder(self.spinValor_2, self.spinValor_3)
        Form.setTabOrder(self.spinValor_3, self.textComentario)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Adicionar Gasto Recorrente"))
        self.labelGasto.setText(_translate("Form", "Saída"))
        self.labelCategoria_2.setText(_translate("Form", "Tipo"))
        self.comboCategoria_2.setItemText(0, _translate("Form", "Conta"))
        self.comboCategoria_2.setItemText(1, _translate("Form", "Assinatura"))
        self.comboCategoria_2.setItemText(2, _translate("Form", "Prestação"))
        self.labelCategoria.setText(_translate("Form", "Categoria"))
        self.labelSub.setText(_translate("Form", "Sub-categoria"))
        self.labelValor.setText(_translate("Form", "Valor (por mês)"))
        self.labelValor_2.setText(_translate("Form", "R$"))
        self.labelValor_3.setText(_translate("Form", "Parcelas restantes"))
        self.labelPrevisao.setText(_translate("Form", "Dia de vencimento"))
        self.labelComentario.setText(_translate("Form", "Comentário"))

