# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recorrentes.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(495, 300)
        Form.setMinimumSize(QtCore.QSize(200, 300))
        Form.setMaximumSize(QtCore.QSize(9999, 9999))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelGasto = QtWidgets.QLabel(Form)
        self.labelGasto.setObjectName("labelGasto")
        self.horizontalLayout_2.addWidget(self.labelGasto)
        self.inputGasto = QtWidgets.QLineEdit(Form)
        self.inputGasto.setObjectName("inputGasto")
        self.horizontalLayout_2.addWidget(self.inputGasto)
        self.labelCategoria_2 = QtWidgets.QLabel(Form)
        self.labelCategoria_2.setObjectName("labelCategoria_2")
        self.horizontalLayout_2.addWidget(self.labelCategoria_2)
        self.comboTipo = QtWidgets.QComboBox(Form)
        self.comboTipo.setObjectName("comboTipo")
        self.comboTipo.addItem("")
        self.comboTipo.addItem("")
        self.comboTipo.addItem("")
        self.horizontalLayout_2.addWidget(self.comboTipo)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelCategoria = QtWidgets.QLabel(Form)
        self.labelCategoria.setObjectName("labelCategoria")
        self.horizontalLayout_3.addWidget(self.labelCategoria)
        self.comboCategoria = QtWidgets.QComboBox(Form)
        self.comboCategoria.setObjectName("comboCategoria")
        self.horizontalLayout_3.addWidget(self.comboCategoria)
        self.labelSub = QtWidgets.QLabel(Form)
        self.labelSub.setObjectName("labelSub")
        self.horizontalLayout_3.addWidget(self.labelSub)
        self.comboSub = QtWidgets.QComboBox(Form)
        self.comboSub.setObjectName("comboSub")
        self.horizontalLayout_3.addWidget(self.comboSub)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelValor = QtWidgets.QLabel(Form)
        self.labelValor.setObjectName("labelValor")
        self.horizontalLayout_4.addWidget(self.labelValor)
        self.labelRS = QtWidgets.QLabel(Form)
        self.labelRS.setObjectName("labelRS")
        self.horizontalLayout_4.addWidget(self.labelRS)
        self.spinValor = QtWidgets.QDoubleSpinBox(Form)
        self.spinValor.setDecimals(2)
        self.spinValor.setMaximum(99999.99)
        self.spinValor.setProperty("value", 0.0)
        self.spinValor.setObjectName("spinValor")
        self.horizontalLayout_4.addWidget(self.spinValor)
        self.labelParcelas = QtWidgets.QLabel(Form)
        self.labelParcelas.setObjectName("labelParcelas")
        self.horizontalLayout_4.addWidget(self.labelParcelas)
        self.spinParcelas = QtWidgets.QSpinBox(Form)
        self.spinParcelas.setObjectName("spinParcelas")
        self.horizontalLayout_4.addWidget(self.spinParcelas)
        self.labelPrevisao = QtWidgets.QLabel(Form)
        self.labelPrevisao.setObjectName("labelPrevisao")
        self.horizontalLayout_4.addWidget(self.labelPrevisao)
        self.spinVencimento = QtWidgets.QSpinBox(Form)
        self.spinVencimento.setObjectName("spinVencimento")
        self.horizontalLayout_4.addWidget(self.spinVencimento)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.labelComentario = QtWidgets.QLabel(Form)
        self.labelComentario.setObjectName("labelComentario")
        self.verticalLayout.addWidget(self.labelComentario)
        self.textComentario = QtWidgets.QTextEdit(Form)
        self.textComentario.setObjectName("textComentario")
        self.verticalLayout.addWidget(self.textComentario)
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.inputGasto, self.comboTipo)
        Form.setTabOrder(self.comboTipo, self.comboCategoria)
        Form.setTabOrder(self.comboCategoria, self.comboSub)
        Form.setTabOrder(self.comboSub, self.spinValor)
        Form.setTabOrder(self.spinValor, self.spinParcelas)
        Form.setTabOrder(self.spinParcelas, self.spinVencimento)
        Form.setTabOrder(self.spinVencimento, self.textComentario)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Adicionar Gasto Recorrente"))
        self.labelGasto.setText(_translate("Form", "Saída"))
        self.labelCategoria_2.setText(_translate("Form", "Tipo"))
        self.comboTipo.setItemText(0, _translate("Form", "Conta"))
        self.comboTipo.setItemText(1, _translate("Form", "Assinatura"))
        self.comboTipo.setItemText(2, _translate("Form", "Prestação"))
        self.labelCategoria.setText(_translate("Form", "Categoria"))
        self.labelSub.setText(_translate("Form", "Sub-categoria"))
        self.labelValor.setText(_translate("Form", "Valor (por mês)"))
        self.labelRS.setText(_translate("Form", "R$"))
        self.labelParcelas.setText(_translate("Form", "Parcelas restantes"))
        self.labelPrevisao.setText(_translate("Form", "Dia de vencimento"))
        self.labelComentario.setText(_translate("Form", "Comentário"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

